### ISSUE TITLE
Tearing/Vsync issues in Cinnamon/Clutter

### ISSUE THREAD

**Issue by ghost** [linuxmint/Cinnamon#3423]
Running nVidia hardware on multiple machines, and along with other nVidia users I have bad screen tearing in Cinnamon/Clutter unless the game has a VSYNC option which forces it on, then things work fine.  For some reason VLC doesn't have tearing that I can notice, but Totem always has horrible tearing.

The solution being done by several users right now is to switch to the Compton compositor instead and forcing on VSYNC for everything through that, but can't we get an option to force it on for Cinnamon instead?  For some reason the usual Cluttter options do NOT force on VSYNC.  See the following threads on the Linux Mint forums and Reddit:

http://forums.linuxmint.com/viewtopic.php?f=59&t=171020
http://www.reddit.com/r/linux_gaming/comments/28skqt/psa_do_you_have_screen_tearing_issues_only_in/

Also found this suggestion to add a VSYNC option to Cinnamon options, but if that option doesn't work anyway then that won't fix the problem.

https://github.com/linuxmint/Cinnamon/issues/1773

Using nVidia closed driver.

**Comment by tobami** [comment]
On Linux Mint 17.1 and the integrated graphics of an Intel Core i5-3450 the tearing happens on desktop applications like Sublime or Firefox. On an i5 laptop, it also happens even in VLC, horribly so.

**Comment by AXDOOMER** [comment]
When I watch videos or play games, the screen gets updated inside the windows I see a triangle in the lower-left and another in the upper-right inside of the rectangular part of the screen that gets updated. My card is an "Integrated Intel Graphics Media Accelerator 3100". It is another issue with synchronisation, else I wouldn't see two triangles in portions of the screen that get updated. My "xorg.conf" file in "/etc/X11/" is empty, so I don't know what to do about that and how I am going to fix this problem.

**Comment by Swiftpaw** [comment]
Hopefully this issue is gone in Mint 17.3 for everyone, it's been gone for me for a long while but I'm still on NVIDIA.

**Comment by LiamDawe** [comment]
@Swiftpaw I do still get tearing on Cinnamon with Nvidia on my 4K monitor, but not my 1080p monitor.

What settings are you using to remove tearing?

**Comment by Knuffre** [comment]
I get tearing on both of my monitors using a GTX 760 and Linux Mint 17.2 Rafaela.

If I have understood it correctly; screen tearing is a guarranteed issue (at least for Linux) if your GPU is of the Kepler architecture and you're not using a global Vsync.
My problem is that I can't find any Vsync setting in Nvidia X Server Settings, and I'm a Linux-newbie so I don't know of any other softwares that can do that.

**Comment by gshegosh** [comment]
I get diagonal screen tearing in Firefox in Linux Mint 18 Cinnamon beta.

`
➜  ~ inxi -Fxz
System:    Host: lapgk Kernel: 4.4.0-24-generic x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.5 (Gtk 3.18.9-1ubuntu3)
           Distro: Linux Mint 18 Sarah
Machine:   System: Dell (portable) product: Latitude E6540 v: 00
           Mobo: Dell model: N/A Bios: Dell v: A16 date: 09/01/2015
CPU:       Quad core Intel Core i7-4800MQ (-HT-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 21550
           clock speeds: max: 3700 MHz 1: 2716 MHz 2: 2700 MHz 3: 2700 MHz
           4: 2700 MHz 5: 2711 MHz 6: 2725 MHz 7: 2847 MHz 8: 2704 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           bus-ID: 00:02.0
           Card-2: Advanced Micro Devices [AMD/ATI] Mars XTX [Radeon HD 8790M]
           bus-ID: 01:00.0
           Display Server: X.Org 1.18.3 driver: intel
           Resolution: 2560x1440@59.95hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Audio:     Card-1 Intel 8 Series/C220 Series High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Card-2 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0
           Card-3 Logitech Webcam C270 driver: USB Audio usb-ID: 003-039
           Sound: Advanced Linux Sound Architecture v: k4.4.0-24-generic
Network:   Card-1: Intel Ethernet Connection I217-LM
           driver: e1000e v: 3.2.6-k port: f080 bus-ID: 00:19.0
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Intel Centrino Ultimate-N 6300
           driver: iwlwifi bus-ID: 03:00.0
           IF: wlp3s0 state: up mac: <filter>
Drives:    HDD Total Size: 512.1GB (54.6% used)
           ID-1: /dev/sda model: Crucial_CT512MX1 size: 512.1GB
           ID-2: /dev/mmcblk0 model: N/A size: 64.3GB
Partition: ID-1: / size: 470G used: 235G (53%) fs: ext4 dev: /dev/dm-1
           ID-2: /boot size: 236M used: 60M (27%) fs: ext2 dev: /dev/sda1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 50.0C mobo: N/A gpu: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 283 Uptime: 4 days Memory: 5866.6/15952.7MB
           Init: systemd runlevel: 5 Gcc sys: 5.3.1
           Client: Shell (zsh 5.1.1) inxi: 2.2.35 
`

**Comment by jkors** [comment]
I also get diagonal screen tearing in Firefox, using Intel integrated graphics (Intel® HD Graphics 520).

>System:    Host: nix-johan Kernel: 4.4.0-28-generic x86_64 (64 bit gcc: 5.3.1)
           Desktop: Cinnamon 3.0.6 (Gtk 3.18.9-1ubuntu3)
           Distro: Linux Mint 18 Sarah
Machine:   System: Dell (portable) product: XPS 13 9350
           Mobo: Dell model: 07TYC2 v: A01
           Bios: Dell v: 1.4.4 date: 06/14/2016
CPU:       Dual core Intel Core i5-6200U (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9600
           clock speeds: max: 2800 MHz 1: 790 MHz 2: 781 MHz 3: 733 MHz
           4: 799 MHz
Graphics:  Card: Intel Sky Lake Integrated Graphics bus-ID: 00:02.0
           Display Server: X.Org 1.18.3 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1920x1080@59.93hz
           GLX Renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes
Info:      Processes: 218 Uptime: 9:13 Memory: 1221.5/7608.6MB
           Init: systemd runlevel: 5 Gcc sys: 5.3.1
           Client: Shell (bash 4.3.421) inxi: 2.2.35

**Comment by Frogging101** [comment]
I know exactly what issue you guys are talking about. I fixed it by using the generic modesetting Xorg module instead of the Intel one. This was achieved by simply removing the module:
`sudo apt-get remove xserver-xorg-video-intel`

Relevant reddit thread that prompted me to try this: https://www.reddit.com/r/archlinux/comments/4cojj9/it_is_probably_time_to_ditch_xf86videointel/

**Comment by johankor** [comment]
@Frogging101 Thank you for letting us know. This seems to have solved my tearing issue in Firefox, and presumably system-wide as well. At the first boot after having removed the module, my system got stuck at the Mint boot animation. Fortunately, after a hard-shutdown, it booted without any issues.

**Comment by emrys-s** [comment]
@Frogging101 Strange solution, worked for me too

**Comment by NodokaMurmevent** [comment]
not worked for me :
mint 18 cinnamon
kernel 4.4.0
 Nvidia 860m + intel
i have try this too :
[https://forums.linuxmint.com/viewtopic.php?f=206&t=136859?f=206&t=136859#p743478](url)

**Comment by mainmachine** [comment]
@NodokaMurmevent - you need to use bumblebee or prime. I've got almost the same laptop (Acer Aspire V17, i7-4720HQ and Nvidia 860M) and I could never use the Nvidia only without tearing. The reason is the Nvidia uses the Intel's framebuffer (or something like that) so if you try to use *only* the Nvidia, there's no control of the framebuffer to vsync, and you get tearing. I use Bumblebee and Primusrun to run stuff on the Nvidia on demand, and no tearing. :)

Bumblee isn't perfect, though, and I haven't been able to fully disable the Nvidia when not in use, so there's no real power savings... :/

**Comment by NodokaMurmevent** [comment]
thanks for the infos ! I only use the switch in the drivers. I will try Bumblebee.

**Comment by ngustavo** [comment]
> sudo apt-get remove xserver-xorg-video-intel
That totally worked for me. Thank you. I think they could add that fix as default.
I got Mint 18, GTX 650, i5-3330

**Comment by thorsummoner** [comment]
I don't know if this contributes to the conversation any. When I try
```
# Cinnamon 2.8.8
CLUTTER_VBLANK=False cinnamon --replace --clutter-show-fps --clutter-default-fps=75
```
I got
```
*** Error in `cinnamon': double free or corruption (!prev): 0x00005646fa5578e0 ***
```
I was trying to turn Vblank off because cinnamon was limiting clutter and programs (glxgears) to ~60FPS with a tv plugged in over HDMI (that I wasn't actively using); I would like to find a way to run programs at the native 75 FPS/Hz of my primary display without physically unpluggin the hdmi cable. I was extra frustrated because the Nvidia Control Panel had the 75Hz monitor selected for its "XServer XVideo" "Sync to this device" but things still run at 60FPS. 

But I dont really understand video well enough to know if forcing cinnamon to run at the higher 75FPS would make for issues for a 60Hz display. I didn't think so, But its the only reason I can figure why Clutter/Cinnamon would opt to use the lesser clock.

**Comment by sibe39** [comment]
j'ai le même problème pour ma part. (tearing diagonal ds firefox avec carte intel).

**Comment by echuber2** [comment]
@sibe39 I had the same problem but I was able to solve it with the `uxa` acceleration mode. I posted some instructions and a conf file. https://github.com/echuber2/linux-settings

**Comment by sibe39** [comment]
@echuber2 With "uxa", the "MDM Session" lag (very low), it's not possible ! (but the tearing diagonal in firefox disappears with uxa).
There is only "sna" and "glamor" which works correctly (but with diagonal tearing in firefox...).

A another solution to solve the problem of diagonal tearing by with sna in conf file ?

**Comment by echuber2** [comment]
@sibe39 You're right, it seems to have poor latency. It's as though the desktop framerate has dropped to 30fps. I've just committed a new version of the conf that uses glamor and seems to work more smoothly. Can you try it out? If this still doesn't work, I'm going to try to get `modesetting` to work or try other driver PPAs. (Alternatively, I could just stop using Cinnamon. I don't think people are having these problems with other WMs+Compton, but I'd rather not switch.)

**Comment by echuber2** [comment]
Also, I did put the CLUTTER tweaks in /etc/environment. With that and the conf, it's currently not tearing and mostly smooth, with occasional lag.

**Comment by echuber2** [comment]
Actually the issue with lag gets worse when the CLUTTER tweaks are added in uxa and glamor modes. I'm getting the best result with glamor+no clutter tweaks right now.

**Comment by sibe39** [comment]
@echuber2 The diagonal tearing is specific for firefox (No problem with chromium or other application : vlc, mplayer etc...). 
Best for the moment is : go in "about:config" (in firefox) and for "gfx.xrender.enabled" put "true" and no tearing. (There may be some scratches that appear but it is less embarrassing and rare).

The diagonal tearing problem in firefox is also present in "Gnome 3/Gnome Shell" (not specific cinnamon).

PS : With xfce, compton is not necessary with intel card for not to have of tearing, this file in /etc/X11/xorg.conf.d is enough : https://github.com/sibe39/scripts_divers/blob/master/xorg_intel.conf

Summary of opportunities against the tearing : https://raw.githubusercontent.com/sibe39/Doc/master/regler_probleme_tearing.txt

**Comment by echuber2** [comment]
@sibe39 Thank you! (I'll update my readme later...) What I did was: update to LM18.1, get 4.8 kernel and latest nvidia drivers, setup bumblebee completely, leave SNA as the default mode, and crucially, turn on gfx.xrender.enabled to stop the diagonal problem in Firefox. This does work better than any of my xorg.conf suggestions.

**Comment by kvnxiao** [comment]
I'm continuing to have this issue with what seems like no solution in sight. I have a Dell XPS 15 laptop with NVIDIA Optimus running on a Skylake Intel HD 530 and a GTX 960M combo.

The issue seems to occur when I have bumblebee installed for GPU switching, which should default to running off the Intel GPU. There is no tearing if I don't have bumblebee installed and default to using the NVIDIA GPU. If I choose to set the intel GPU to use the `intel` driver rather than leaving it at `modesetting`, I get insane graphical artifacts regardless of the settings I choose.

Is there some setting in the compositor that can be changed? I've installed KDE on the side and tested the same configuration with bumblebee and there is no tearing whatsoever. This issue only persists on Cinnamon.

**Comment by mainmachine** [comment]
In nvidia-settings, do you have it configured to sync to your display?

**Comment by echuber2** [comment]
Not sure what distro you are running, but you could try reinstalling and reconfiguring Bumblebee with the procedure described here. http://lenovolinux.blogspot.com.au/2018/02/bumblebee-on-lenovo-t440p-nvidia-gt.html

**Comment by kvnxiao** [comment]
@mainmachine It's not possible to configure nvidia-settings to sync with display since you cannot access advanced settings when using an Optimus laptop and have bumblebee installed. I'm also not sure why that would change anything since the video output should be coming through the Intel integrated GPU?

![image](https://user-images.githubusercontent.com/14130413/35998628-3bc5eaaa-0ceb-11e8-827d-24eecbbcdd39.png)

@echuber2 I'm running on the latest Arch Linux.

**Comment by echuber2** [comment]
Might want to check your xorg logs for errors and warnings, and still peruse the link I posted above to make sure your modules are being updated correctly (although I'm sure it's different for Arch)

**Comment by kvnxiao** [comment]
@echuber2 checking Xorg logs for errors and warnings specific to what problem?

**Comment by mainmachine** [comment]
@kvnxiao - Yes, the Intel GPU should be doing this, but check on the "X Server XVideo Settings" tab. I'm typing this from a Optimus laptop and I don't have tearing, so there's hope. :)

I am using modesetting driver as well, looking through my Xorg.0.log...

Can you post your Xorg.0.log somewhere?

**Comment by nick-s-b** [comment]
I've been trying for years and I've never been able to eliminate Vsync/tearing issues on my machine. It's not as bad as it used to, but I still occasionally notice it when I play some high-bitrate videos. I use Nvidia graphics only.

If you guys go to https://www.vsynctester.com and run the test, can you see the red or cyan  vsync in the right corner? I haven't been able to eliminate that no matter what "fix" or browser I tried.

**Comment by kvnxiao** [comment]
@mainmachine Here is my `Xorg.0.log` file:
[xorg.0.log](https://github.com/linuxmint/Cinnamon/files/1708893/xorg.0.log)

In the `X Server XVideo Settings` tab, it says `Currently synced to display: Unknown`
![image](https://user-images.githubusercontent.com/14130413/35999689-b2f8e17e-0cee-11e8-8dcd-e10688c621ab.png)

**Comment by mainmachine** [comment]
@echuber2 - that looks like a good resource for that specific hardware; here's another that I've found invaluable (it is specific to Ubuntu, though):

http://danielteichman.blogspot.com/2017/03/how-to-install-bumblebee-on-ubuntu-1604.html

@kvnxiao - it's probably worth looking over your config versus these two links.

I'm also using the latest stable Mesa (17.3.2) - what are you using?

**Comment by kvnxiao** [comment]
@mainmachine @echuber2 

Good news! It seems like after some tinkering I actually got it to work! No more diagonal screen tearing visible system wide.

I'm not sure if this applies to other optimus users with older integrated intel GPUs, but **for Skylake users with Intel HD 530**, this is what I found that helped me fixed the problem.
I followed danalec's post in this thread here: https://bbs.archlinux.org/viewtopic.php?id=208299
Reinstalled `xf86-video-intel` and added a `20-intel.conf` to my xorg configurations to use `intel` over `modesetting` (for the `TearFree=true` setting, which only works in `AccelMethod=sna`):
```
Section "Device"
	Identifier  "Intel Graphics"
	Driver      "intel"
	Option      "DRI" "3"
	Option      "AccelMethod"  "sna"
	Option      "TearFree" "true"
EndSection
```

Since I use GRUB, I then added these kernel parameters to `/etc/default/grub` in the `GRUB_CMDLINE_LINUX_DEFAULT` line:

```
modprobe.blacklist=nouveau i915.enable_rc6=0 i915.enable_psr=0 i915.preliminary_hw_support=1 i915.enable_hd_vgaarb=1 intel_idle.max_cstate=1
```

And regenerated my grub configuration file, then rebooted.

**Comment by mainmachine** [comment]
@kvnxiao - the only difference I've seen that looks notable is that your Xorg is this:
```[     2.393] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so```
...I have this xorg module, but it does not get loaded. AFAIK with Bumblebee you should not have a /etc/X11/xorg.conf, this is handled by Bumblebee for the Nvidia GPU with /etc/bumblebee/*.conf

Do you have an xorg.conf in /etc/X11/ and if so, what's in it? If you have any lines specifying or loading the "intel" module, then I'd comment and restart...

**Comment by mainmachine** [comment]
@kvnxiao - that's great! 👍 

As far as this issue goes globally, it seems as if more and more vsync is getting solved at the driver level. This has certainly been my experience with Nvidia, AMD and Intel, on both Nvidia proprietary and Mesa... maybe this isn't an issue for Cinnamon (or any other DE) specifically anymore...?

**Comment by kvnxiao** [comment]
@mainmachine Well... the reason I asked for help originally was because while on the `modesetting` driver for the integrated intel GPU, there didn't appear to be any screen tearing when I was testing in KDE. Going back to Cinnamon, there's horrible screen tearing unless I use the `intel` driver and apply the changes I listed in the above post.

To me that seemed like a DE issue. If while keeping the system configuration constant, swapping to a different DE showed no screen tearing, but swapping back and screen tearing shows up again.

**Comment by zor1984qq** [comment]
These doesn't help me out on my radeon r5 230 1Gb VRAM caicos GPU. I have no such things with couple of others DE's to be honest the only DE which has these issue is Cinnamon.

**Comment by cppcooper** [comment]
This problem is still quite alive and well. Must be some complicated for it to have a 6+ year span.

**Comment by echuber2** [comment]
@cppcooper 

Can you be more specific about what symptoms you're seeing and what configuration you have, now?

**Comment by cppcooper** [comment]
I see vsync tearing in cinnamon, the issue subsides if I start the session with xfce instead.
I am running Archlinux, I do not recall what the kernel version is. I can say I cloned the repo and built it this last weekend.
I have tried numerous potential remedies, but the only one that works is using xfce which is unfortunate because I prefer the panels and default hotkeys in Cinnamon. Switching the vsync method, nouvea/nvidia drivers were both tried, tried the different composition pipeline options in the nvidia settings, etc.

I only consider it a problem inside firefox when watching videos. I even tried some firefox specific fixes, which I figured might work since VLC doesn't seem to suffer as badly from it. In fact any time I think I've seen tearing I'm not sure if it was or not, so it might as well be considered tear-free at that point (VLC that is).

Nvidia GT 710

**Comment by AlpakaSiedler** [comment]
I have tearing in Linux Mint 19.3 (Cinnamon, 64-bit) with Nvidia GTX 1060 (3GB) (driver: 440.48.02), using desktop applications such as firefox, as well as in games (i recently tried CounterStrike:CZ, Torchlight 2, No Man's Sky and various different Unity3d Games, also self made Unity3d Games). 

To solve this, i tried what they said here: https://github.com/linuxmint/Cinnamon/issues/3355
also added "ForceFullCompositionPipeline" to both of my monitors. 

I've read that it should be less issue on MATE, but i would prefer to stay with Cinnamon.

**Comment by leigh123linux** [comment]
> I have tearing in Linux Mint 19.3 (Cinnamon, 64-bit) with Nvidia GTX 1060 (3GB) (driver: 440.48.02), using desktop applications such as firefox, as well as in games (i recently tried CounterStrike:CZ, Torchlight 2, No Man's Sky and various different Unity3d Games, also self made Unity3d Games).
> 

Why do you need the nvidia beta vulkan driver?, ubuntu vulkan packages aren't new enough to benefit from the new extensions.

> To solve this, i tried what they said here: #3355
> also added "ForceFullCompositionPipeline" to both of my monitors.
> 

I doubt adding that option will help with the newer nvidia drivers

> I've read that it should be less issue on MATE, but i would prefer to stay with Cinnamon.

**Comment by AlpakaSiedler** [comment]
@leigh123linux 
the newest driver was recommended in a forum cause i had problems with Unity3d using Vulkan and No Man's Sky using also only vulkan.

**Comment by genachka** [comment]
Seeing the same problem with Nvidia RTX 2070 on Ubuntu 19.10 and Cinnamon 4.2.4 (though same was with previous versions for the past year+) and as others have tried ForceFullCompositionPipeline and other settings to no avail. Beyond it be annoying for me, apparently it's pretty bad on web meettngs - I need to be on zoom often and share my screen which  makes the attendees see the desktop or window or I'm sharing disappear and show my backend and then reappear periodically. After months of trying to resolve this, regrettably I'd had to switch to the default GNOME (3.34.2) and everything has been fine but I do miss my Cinnamon. Would love to see a fix for this.

**Comment by echuber2** [comment]
Have you tried the various Vsync modes in the control panel?

https://www.reddit.com/r/CinnamonDE/comments/dx4lyk/vsync_method/

**Comment by cppcooper** [comment]
Honestly I am skeptical the vsync modes do anything, there is no discernible difference between any of them for me. After rebooting between changing the modes.

**Comment by echuber2** [comment]
Check the source if you're skeptical. They do something; I saw it make a difference on one of my machines instantly after changing the setting. (That did not have an nvidia GPU though.) If anything I bet this all comes down the drivers you have installed. Although, if there is something distinctively wrong with Cinnamon's vsync then I'd also like to know about it.

**Comment by AlpakaSiedler** [comment]
I also tried different vsync modes but it did not make a noticeable difference. I also tried different driver versions, the recommended one, the newest, older stable drivers that were recommended by community users, nothing helped.

**Comment by genachka** [comment]
@echuber2 I too have tried those various Vsync modes and followed the steps in the link. No change. I'm on an Nvidia. And I don't think it's the drivers as I don't have this issue anymore with GNOME :( Open to trying other things as would love to switch back.
