### ISSUE TITLE
Cinnamon 2.4.5 LM 17.1 CPU Usage

### ISSUE THREAD

**Issue by kram1t** [linuxmint/Cinnamon#3736]
Good Day All,

Cpu usage on my system goes up to 48+% after some period of inactivity. I can clear this by logging out and back in (restarting X is how I think of that). This is an older PC with Intel onboard graphics. CPU usage monitored with top. 

`lspci | grep -i vga` =
00:02.0 VGA compatible controller: Intel Corporation 82945G/GZ Integrated Graphics Controller (rev 02)
`uname -r` = 
3.13.0-37-generic

Any tips on how to further diagnose this problem would be greatly appreciated.

-Mark

**Comment by BartonCline** [comment]
Just started digging into the cause of keyboard too hot to bare on non-Mint single DE install on older laptop...
$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)
Dual core T4300 2.1 GHz
Running cool and quiet at the moment several minutes after a reboot - haven't tried log out, back in.
I'll be following this issue and doing some digging.

**Comment by RatanRSur** [comment]
Also having this issue, like another user, minimizing windows makes cinnamon drop from top processes.

With chrome and system monitor, cinnamon averages 20-30%
2.5GHz quad-core Intel Core i7 processor 
Macbook Pro

Xorg is also averaging the same amount but doesn't drop with minimization.

**Comment by afita** [comment]
Cinnamon CPU usage drops when I minimize Totem in my case as well.

**Comment by scesbron** [comment]
Same problem for me. I tried to use xfce and mate on the same pc and don't have the problem with these DE.

cpu also drop for me if I minimize all windows

The problem first occurs while using firefox, I tried to use chromium but the problem also occurs with chromium

**Comment by leigh123linux** [comment]
@scesbron 

Mate and xfce aren't valid examples as there not 3d accelerated DE's, can you reproduce using compiz, gnome-shell or with kde compositing?

**Comment by waleedasif322** [comment]
same problem as everyone else.

ibm thinkpad x1

fresh install of linux mint, just changed some settings for switching between windows and workspaces

**Comment by Anachron** [comment]
Same with me, minimizing the movie will drop the CPU load from 20% to 2-5%.

**Comment by java-artisan** [comment]
Still the same here. It's getting on my nerves really - because the fans kick in after a while. Making loud noise while the thing is literally sitting idle. I really thought Mint was better than that ... 

Is there really nothing we can do to help ??? Surely, seeing so many people having this problem. I'm no Linux hacker, but if somebody from Mint can walk me through collecting data, I'd be happy to oblige. 

Because this is non-sense ! Running a cpu 100% for doing ... nothing at all.

**Comment by Anachron** [comment]
Same with me, fan spins crazily for a few seconds and then is finished.

**Comment by branman4** [comment]
Same problem as the original post.......after the computer is lef idle for more than10 minutes, cinnamon goes wild with CPU

**Comment by java-artisan** [comment]
Probably nothing import : nobody from Mint bothered to answer. I'm out of Mint.

**Comment by gregeva** [comment]
Also experiencing this issue, however infrequently.  The two times I have seen this, my laptop was almost completely unusable (i5 4Gb SSD).  Accompanying this `cinnamon --replace` process was another which seems to just run indefinitely and restarts even after reboots.

`/usr/bin/python /usr/sbin/update-apt-xapian-index --quiet`

I saw this behaviour on the afternoons of Monday March 30, and Monday May 11.  Perhaps it is related to a scheduled task or online service not being available.

After having a look through the open issues, I wonder if this is not related to issue #4072, as Alt-Tab and Menu button were no longer functioning at all, although I could eventually select other windows and activate the menu via clicking.

**Comment by poserman** [comment]
Reporting the same issue. Up to date Mint. 

From top: 
 3245 poserman    20   0 1854772 365796  17048 S  31,9  4,5   1062:30 cinnamon                                                     
 3245 poserman    20   0 1854772 365796  17048 R  28,9  4,5   1062:31 cinnamon                                                     
 3245 poserman    20   0 1854772 365800  17048 S  29,3  4,5   1062:32 cinnamon                                                     
 3245 poserman    20   0 1854780 365844  17052 S  24,9  4,5   1062:32 cinnamon                                                     
 3245 poserman    20   0 1854780 365844  17052 R  15,9  4,5   1062:33 cinnamon                                                     
 3245 poserman    20   0 1854780 365844  17052 S  15,9  4,5   1062:33 cinnamon                                                     
 3245 poserman    20   0 1854780 365848  17052 R  21,6  4,5   1062:34 cinnamon                                                     
 3245 poserman    20   0 1855128 365816  17012 S  52,2  4,5   1062:36 cinnamon  

From ps aux
poserman    2747  0.0  0.0 395436  4104 ?        Ssl  Jul19   0:01 cinnamon-session --session cinnamon
poserman    2972  0.1  0.7 988692 60680 ?        Sl   Jul19   3:04 /usr/lib/cinnamon-settings-daemon/cinnamon-settings-daemon
poserman    3239  0.0  0.0 151108  7312 ?        S    Jul19   0:00 /usr/bin/python /usr/bin/cinnamon-launcher
poserman    3245 36.1  4.5 1855936 367756 ?      Rl   Jul19 1062:51 cinnamon --replace
poserman    3251  0.0  0.0 386960  1380 ?        Sl   Jul19   0:00 /usr/lib/cinnamon-settings-daemon/csd-printer
poserman    3374  0.0  0.1 420284 14304 ?        Sl   Jul19   1:40 cinnamon-screensaver
poserman   22136  0.0  0.0  11748   944 pts/3    S+   20:35   0:00 grep --colour=auto cinnamon

**Comment by gregeva** [comment]
I had this same issue come back up on Sunday August  2, and Monday August 3, 2015.  I reiterate that it is really strange that my laptop works fine most of the time, and then all of a sudden for a couple days it is completely unusable due to this 'cinnamon --replace' process hogging the resources.  I can barely even click on the menu button and get it to restart, and the problem just resurfaces after a restart.

ALAS... I have new insight to share however.  I discovered that the problem disappears if I unplug the power cord (and run on battery).  It slowly comes back when I plug back in however.  How strange!

**Comment by kowalcj0** [comment]
In my case, I've noticed that minimizing Foobar2000 running under Wine, made the `cinnamon --replace` cpu load drop from 60-70% (when foobar is maximized and spectrogram and spectrum visualization are on) or 30-40% (when foobar's window takes around 50% of the screen) to 5-15%. 
Turning off the spectrogram reduces the load by ~15%, and spectrum visualization by 30-40%.

**Comment by lea-anthony** [comment]
I too have experienced this issue. For me, it was running chrome-remote-desktop which itself tries to launch cinnamon on connection. To test, I installed MATE, logged back in using that desktop and still saw cinnamon-settings caning the CPU. Repeated killing of the process didn't help as it seemed to resurrect each time. However, an `/etc/init.d/chrome-remote-desktop stop` totally stopped it. Although I know it isn't CRDP itself, I'm wondering if there's a clue there for someone more familiar with cinnamon. To my eyes, it *seems* to be related to multiple launching of cinnamon. Hope that helps. Cheers.

**Comment by zds** [comment]
I'm having the same issue on Ubuntu 15.10. I'm seeing cinnamon use 46-53% of all the CPU capacity; that's three cores. My hunch is that's somehow related to GPU acceleration; I'm using some crappy discreet GeForce, so anything that tries to "accelerate" using it will only stir trouble.

Is there a way to stop cinnamon from accelerating using GPU? Is there a log to tell what exactly it's doing? It seems bizarre a process would do computation so heavy it needs three cores for hours straight and not write a single line of log about what it is trying to do.

**Comment by galik** [comment]
I have high CPU usage in Cinnamon every time I run a Java application. Closing down all Java processes seems to fix the problem. Unfortunately some of my critical software is in Java.

**Comment by gregeva** [comment]
An update on my strange case-- it is solved... nothing to do with Linux Mint or Cinnamon.  I had been given an extra HP power supply... it is supposedly outputting the proper voltages, but is rated as 18.5V vs. their newer 19V ones.  It seems that a slightly different line voltage was causing the CPU to behave EXTREMELY slowly, and eventually even stopped charging.  Replacing the spare power supply with a new one solved the my issue and I am no longer seeing any major slowdowns from Mint or Cinnamon.

**Comment by gone** [comment]
I also have this problem - Also a thinkpad carbon.

**Comment by Dreezert** [comment]
Hello, I had the same issue and this solved it: 

"Moved ~/.cinnamon to ~/.cinnamon-bak." and then rebooted.

"Was probably an issue with a previous version of ~/.cinnamon, since that folder has been around for quite some time."

Source: https://bbs.archlinux.org/viewtopic.php?id=216432

**Comment by maxkoryukov** [comment]
the issue still here.

```
System:    Kernel: 4.8.0 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3) Distro: Linux Mint 18.2 Sonya
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0416
           Card-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]
           bus-ID: 01:00.0 chip-ID: 10de:1140
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa) FAILED: nouveau
           Resolution: 1366x768@60.00hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile GLX Version: 3.0 Mesa 17.0.7 Direct Rendering: Yes
```
Even if the problem is caused by FAILED NVidia driver, why **Cinnamon eats** additional 30-40% CPU when Chromium draws difficult graphics (svg animations, css effects, parralax effect and other). It is not a task for Cinnamon

**Comment by haphaeu** [comment]
Same issue. Three years. Any developer cares to answer with potential solution?

**Comment by Anachron** [comment]
I think you guys should abandom this sinking ship, at least I did.

**Comment by haphaeu** [comment]
Solution proposed by @Dreezert help a lot here. `cinnamon --replace` is still there at top 2 the whole time, but now with much less CPU usage - barely noticeable and fans don't kick in anymore. 

So, not leaving the boat, yet =)

**Comment by bash64** [comment]
renamed the .cinnamon folder. waiting to see if cpu spikes are gone

**Comment by bash64** [comment]
solved: removed two bad panel apps. cpu temperature and disk utilization.
cpu spikes are completely gone.

**Comment by miroslavvidovic** [comment]
I managed to solve this problem by removing "Window List With App Grouping" applet from my panel

**Comment by Vahan86** [comment]
Is this still an issue for those who have had this issue before?

**Comment by haphaeu** [comment]
Well, `cinnamon --replace` still there in top 5 CPU usage, with something like 1-2%, much less noticeable, but still more than for example `conky` or even idle `firefox`.
Running Cinnamon 4.4.8 in Mint 19.3.

**Comment by gregeva** [comment]
I did drop using Mint with Cinnamon (situation changed)... but I also found the source of weirdness experienced.  It was my power supply (HP EliteBook Folio 9470m)... I guess it was on it's way out and was delivering something the CPU/GPU didn't like.  When I was running on battery, CPU usage became normal, when I'd plug in the system ran so slow it was unusable.  This Cinnamon replace task I feel was just one symptom of a deeper problem.  Changing the power supply resolved the issue.

**Comment by taurus-forever** [comment]
I have just upgraded to Linux Mint 20 on my Dell XPS 13 7390, so it is a latest software as for today.
Run "top" and do nothing for 1 minute:

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                
   6684 user    20   0 4190476 221420 108064 S   6.6   1.4  61:40.19 cinnamon --replace 

So, "cinnamon --replace" is never below 5.5% CPU usage. After pressing ALT+TAB for 5 time I have:

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                                                
   6684 user    20   0 4190604 222196 108576 R  46.4   1.4  61:16.94 cinnamon --replace 

which went down to 5.5% in several seconds. I still believe those number are slightly high.
All tests were made with connected power supply. With 8 CPUs I do not expext a lot of issues with high CPU usage, but nice to have it fixed.

P.S. I like Mint 20, it looks stable and finally has DPI per monitor configuration!!! THANK YOU!!!

**Comment by tgaertner** [comment]
I run into this on my Mint 20 (updated from 19.3 without issues). From my observing it happens when coming back from suspend mode (closed laptop lid and opened the next day). Restarting Cinnamon (Alt + F2 -> r) helps - after that cinnamon --replace process stays between 3 and 5% CPU usage.
I have other problems with Cinnamon/Windowmanager after switching Users - in all that cases restarting Cinnamon helps.
Would be great if Cinnamon becomes more stable on all that suspend, hybernate and switch users stuff - this isthere since I use LinuxMint from version 16 on, on several Computers!

**Comment by mrdntgrn** [comment]
I have latest Linux Mint 20.1 with Cinnamon 4.8.6 and can see the issue:
here is my system information: https://termbin.com/g7q3
terminal top command: 
![image](https://user-images.githubusercontent.com/31103575/111451070-7c606380-872a-11eb-8711-a538a9bd3343.png)

**Comment by xavierholt** [comment]
I had a similar problem with high CPU usage.  In my case, it was because Linux didn't recognize my GPU, and Cinnamon fell back to software rendering.  I was able to fix the problem with a GPU driver update.  I've posted more details at https://github.com/linuxmint/cinnamon/issues/9730#issuecomment-2209539490 (that issue may be a duplicate of this one).
