### ISSUE TITLE
Searchbar does not delete its placeholder text in startmenu

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon#4494]
![](http://i.imgur.com/ptWSriy.png)

This is reproducable when focusing [albert](https://github.com/ManuelSchneid3r/albert) and then hitting the hotkey (menu) for the startmenu. Maybe the xprops (of albert) can be of use:

```
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_ABOVE, _NET_WM_STATE_FOCUSED
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x1c00009
XKLAVIER_STATE(INTEGER) = 0, -710660608
WM_STATE(WM_STATE):
        window state: Normal
        icon window: 0x0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_TRANSIENT_FOR(WINDOW): window id # 0x1c00002
_NET_WM_ICON(CARDINAL) =    Icon (96 x 96):
                                             XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Albert"
_NET_WM_NAME(UTF8_STRING) = "Albert"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x4, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x1c00002
WM_HINTS(WM_HINTS):
        Client accepts input or input focus: True
        Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 1295
WM_CLASS(STRING) = "albert", "albert"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
        user specified location: 633, 347
        user specified size: 654 by 75
        program specified minimum size: 654 by 75
        program specified maximum size: 654 by 75
        window gravity: Static
```

**Comment by ManIVIctorious** [comment]
This seems to be resolved in cinnamon 3.0, I don't even get the "Suchbegriff eingeben..." ("Insert searchstring..."?) text, so it doesn't have to be flushed

**Comment by ManuelSchneid3r** [comment]
Nope still a problem. But I found out why. My app hides on focus loss. Slightly delayed. I guess X sends weird messages to the menu when the window of my app hides. Actually this is the reason why I needed to delay the hiding; because key grabs produce focus out events. But thats another story. Just a hint.

**Comment by NikoKrause** [comment]
@ManIVIctorious 
`Suchbegriff eingeben ...` is `Type to search ...`

I am able to see the `Type to search ...` string only on two occasions:
(1) When the menu is open and I click somewhere on the desktop or on the panel to close the menu. Just in the moment where the menu closes, you can see this string flashing for a fraction of one second.
(2) When I press the TAB key the searchbar looses focus. Then you can see the string.

Option (2) is fixed by https://github.com/linuxmint/Cinnamon/pull/5780 

@ManuelSchneid3r 
I don't think that your issue is related to Option (2). But, just to exclude all possibilities, can you try if https://github.com/linuxmint/Cinnamon/pull/5780 fixes your problem?

**Comment by ManuelSchneid3r** [comment]
> I don't think that your issue is related to Option (2). But, just to exclude all possibilities, can you try if #5780  fixes your problem?

Nope. Still there.
![cinnamon-20170118-3](https://cloud.githubusercontent.com/assets/3252315/22070735/54f3403c-dd9d-11e6-999b-49eb3bc883c5.gif)

**Comment by akaIDIOT** [comment]
Finally found this after many google attempts. Behaviour is reproducable in combination with Guake Terminal set to hide on focus loss. Seems to work fine when 'regular windows' are in focus when pressing the menu hotkey, but pressing that when Guake is focussed makes the meny appear, the search bar fade from light to dark and show the "type to search..." placeholder text. Typing after that seems to append the text to the placeholder.

- Mint 18.2
- `guake` 0.8.4-1
- `cinnamon` 3.4.6+sonya
- `xorg` 1:7.7+13ubuntu3
- `xserver-xorg-core` 2:1.18.4-0ubuntu0.3

**Comment by szarnyasg** [comment]
This issue is still present with Linux Mint 19.2 Tina, Guake Terminal 3.0.5, and Cinnamon 4.2.3.

**Comment by bluepostit** [comment]
Still an issue on Linux Mint 19.3 Tricia using [Tilix](https://gnunn1.github.io/tilix-web/) in [Quake mode](https://gnunn1.github.io/tilix-web/manual/quake/).

**Steps to reproduce:**
1. Open Tilix in Quake mode (I use a custom keyboard shortcut)
1. Hit the Start key to raise the Cinnamon menu
1. Try to search by typing

**Observation:**
- Placeholder text ("Type to search...") still remains
- Search input text is appended to "Type to search..."

**Comment by asquartz** [comment]
Still an issue, unfortunately, on Linux Mint 20 Ulyana, with Guake 3.6.3-2 and Cinnamon 4.6.6.
Steps to reproduce as per the above comment.

I also raised this on [linuxmint/cinnamon-menus](https://github.com/linuxmint/cinnamon-menus/issues/34) but I don't know which is the correct location for it.

**Comment by cidwel** [comment]
Still an issue on Mint 20.1. Reproducible when guake is opened.

**Comment by clara2g** [comment]
For me this always happens when Guake is shown and has "hide on lose focus" option enabled

**Comment by asquartz** [comment]
OK, so it's been an issue since 2015, and every new update one or two people come on to state it is still an issue... but it has not even been acknowledged yet.  Is there anything we could/should do to raise awareness?  Otherwise one wonders what is the point of raising the bug in the first place.

**Comment by mtwebster** [comment]
It has been acknowledged - read this entire thread. It's also been worked on a bit, without a solution so far. It's not a trivial issue, unfortunately, though it may appear to be one. On the other hand, it's also not considered 'critical' either. It is on our radar, however.

**Comment by asquartz** [comment]
@mtwebster Thank you, it's good to know it is being worked on.  I admit I missed the "Member" response upthread but was going by the empty fields in the right hand sidebar.

**Comment by Davidy22** [comment]
Made a pull request with a fix for this, I just removed the "type to search" text hint because it only ever appears when the bug is happening and I can type in the field coming straight from guake now.

**Comment by Davidy22** [comment]
@mtwebster I submitted a fix for this 6 year old bug some time ago. There's a fair few people like @asquartz in this issue confirming this, can the pr get looked at at in time for mint 21? I just changed two lines, been using my patched version of the menu since the pr and haven't noticed side effects.yet.

**Comment by icarter09** [comment]
Do not worry. It will get reviewed in due time.
