### ISSUE TITLE
Cinnamon crashes on startup in Arch

### ISSUE THREAD

**Issue by Heliophobe** [linuxmint/Cinnamon#5011]
Recent arch install, everything updated to latest versions. Intel i7 6700k with nvidia 970 gtx video card. When I log in to a cinnamon session it informs me Cinnamon has crashed and is in fallback mode, then proceeds to do nothing but display the crash notification, both in normal and software rendering mode.

Here is what seems relevant from journalctl:

```
Jan 16 21:04:32 derp polkitd[477]: Registered Authentication Agent for unix-session:c4 (system bus name :1.31 [/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1], object path /org/gnome/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jan 16 21:04:32 derp cinnamon-killer-daemon[678]: Bound Cinnamon restart to <Control><Alt>Escape.
Jan 16 21:04:32 derp kernel: traps: canberra-gtk-pl[683] general protection ip:7f9af41687e0 sp:7ffc6d1220e8 error:0 in libpthread-2.22.so[7f9af4156000+18000]
Jan 16 21:04:32 derp dbus-daemon[592]: Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service'
Jan 16 21:04:32 derp systemd[538]: Starting Virtual filesystem metadata service...
Jan 16 21:04:32 derp dbus-daemon[592]: Successfully activated service 'org.gtk.vfs.Metadata'
Jan 16 21:04:32 derp systemd[538]: Started Virtual filesystem metadata service.
Jan 16 21:04:32 derp systemd-coredump[704]: Process 683 (canberra-gtk-pl) of user 1000 dumped core.

                                                   Stack trace of thread 683:
                                                   #0  0x00007f9af41687e0 __lll_unlock_elision (libpthread.so.0)
                                                   #1  0x00007f9ae8b0accc n/a (libEGL_nvidia.so.0)
                                                   #2  0x00007f9ae8a98252 n/a (libEGL_nvidia.so.0)
Jan 16 21:04:32 derp dbus[449]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Jan 16 21:04:32 derp dbus[449]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service failed to load: No such file or directory.
Jan 16 21:04:32 derp dbus[449]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Jan 16 21:04:32 derp dbus[449]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service failed to load: No such file or directory.
Jan 16 21:04:32 derp dbus-daemon[592]: Activating service name='ca.desrt.dconf'
Jan 16 21:04:32 derp dbus-daemon[592]: Successfully activated service 'ca.desrt.dconf'
Jan 16 21:04:32 derp kernel: traps: cinnamon-launch[778] general protection ip:7fa0a6f467e0 sp:7ffe09ad6ce8 error:0 in libpthread-2.22.so[7fa0a6f34000+18000]
Jan 16 21:04:32 derp systemd-coredump[779]: Process 778 (cinnamon-launch) of user 1000 dumped core.

                                                   Stack trace of thread 778:
                                                   #0  0x00007fa0a6f467e0 __lll_unlock_elision (libpthread.so.0)
                                                   #1  0x00007fa099872ccc n/a (libEGL_nvidia.so.0)
                                                   #2  0x00007fa099800252 n/a (libEGL_nvidia.so.0)
Jan 16 21:04:33 derp systemd-coredump[777]: Process 670 (cinnamon) of user 1000 dumped core.

                                                   Stack trace of thread 670:
                                                   #0  0x00007fc335c925f8 raise (libc.so.6)
                                                   #1  0x00007fc335c93a7a abort (libc.so.6)
                                                   #2  0x00007fc33628f8c5 g_assertion_message (libglib-2.0.so.0)
                                                   #3  0x00007fc33628f95a g_assertion_message_expr (libglib-2.0.so.0)
                                                   #4  0x00007fc332fc187e gtk_icon_info_load_icon_finish (libgtk-3.so.0)
                                                   #5  0x00007fc332fc1908 n/a (libgtk-3.so.0)
                                                   #6  0x00007fc336805413 n/a (libgio-2.0.so.0)
                                                   #7  0x00007fc336805449 n/a (libgio-2.0.so.0)
                                                   #8  0x00007fc336269c7a g_main_context_dispatch (libglib-2.0.so.0)
                                                   #9  0x00007fc33626a020 n/a (libglib-2.0.so.0)
                                                   #10 0x00007fc33626a342 g_main_loop_run (libglib-2.0.so.0)
                                                   #11 0x00007fc33764d068 meta_run (libmuffin.so.0)
                                                   #12 0x00000000004017da main (cinnamon)
                                                   #13 0x00007fc335c7f610 __libc_start_main (libc.so.6)
                                                   #14 0x00000000004018b9 n/a (cinnamon)

                                                   Stack trace of thread 727:
                                                   #0  0x00007fc335d43cf9 syscall (libc.so.6)
                                                   #1  0x00007fc3362ae87a g_cond_wait_until (libglib-2.0.so.0)
                                                   #2  0x00007fc33623ea69 n/a (libglib-2.0.so.0)
                                                   #3  0x00007fc336291086 n/a (libglib-2.0.so.0)
                                                   #4  0x00007fc336290715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007fc33600a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007fc335d4813d __clone (libc.so.6)

                                                   Stack trace of thread 671:
                                                   #0  0x00007fc335d3f18d poll (libc.so.6)
                                                   #1  0x00007fc336269fbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007fc33626a0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007fc33626a109 n/a (libglib-2.0.so.0)
                                                   #4  0x00007fc336290715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007fc33600a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007fc335d4813d __clone (libc.so.6)

                                                   Stack trace of thread 772:
                                                   #0  0x00007fc335d43cf9 syscall (libc.so.6)
                                                   #1  0x00007fc3362ae87a g_cond_wait_until (libglib-2.0.so.0)
                                                   #2  0x00007fc33623ea69 n/a (libglib-2.0.so.0)
                                                   #3  0x00007fc336291086 n/a (libglib-2.0.so.0)
                                                   #4  0x00007fc336290715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007fc33600a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007fc335d4813d __clone (libc.so.6)

                                                   Stack trace of thread 673:
                                                   #0  0x00007fc335d3f18d poll (libc.so.6)
                                                   #1  0x00007fc336269fbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007fc33626a0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007fc32282525d n/a (libdconfsettings.so)
                                                   #4  0x00007fc336290715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007fc33600a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007fc335d4813d __clone (libc.so.6)

                                                   Stack trace of thread 675:
                                                   #0  0x00007fc33601007f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007fc32cf074b0 PR_WaitCondVar (libnspr4.so)
                                                   #2  0x00007fc3354ce816 n/a (libmozjs-24.so)
                                                   #3  0x00007fc32cf0cd7b n/a (libnspr4.so)
                                                   #4  0x00007fc33600a4a4 start_thread (libpthread.so.0)
                                                   #5  0x00007fc335d4813d __clone (libc.so.6)
Jan 16 21:04:42 derp login[466]: pam_unix(login:session): session opened for user herp by LOGIN(uid=0)
```
Everything else seems to work fine, just can't get cinnamon running, and googling this has not provided me with useful answers.

**Comment by mjenki03** [comment]
I believe this is an nvidia driver config file problem. I and developers I work with have all had problems after installing the proprietary nvidia driver for support of more than 2 monitors.

I think your problem is this https://github.com/linuxmint/cinnamon-settings-daemon/issues/52

**Comment by leigh123linux** [comment]
This is a nvidia issue

https://devtalk.nvidia.com/default/topic/893325/linux/newest-and-beta-linux-driver-causing-segmentation-fault-core-dumped-on-all-skylake-platforms/

Nvidia beta driver fixes the issue

https://devtalk.nvidia.com/default/topic/908423/unix-graphics-announcements-and-news/linux-solaris-and-freebsd-driver-361-16-beta-/

Fixed a bug in the EGL driver where a mutex was unlocked more than once. This triggers undefined behavior, and in particular, if lock elision is enabled in glibc, may result in a segmentation fault.

**Comment by Heliophobe** [comment]
Hmm, installed nvidia-beta from the AUR (nvidia version 361.18), cinnamon still does not work (still just showing the bluegreen background + crash message), but journalctl is showing a slightly different error: there is no longer any mention of elision:

Is this the same bug, and I'm just missing something?

```
Jan 18 22:04:29 derp dbus[438]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Jan 18 22:04:29 derp dbus[438]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service failed to load: No such file or directory.
Jan 18 22:04:30 derp dbus[438]: [system] Activating via systemd: service name='org.freedesktop.Avahi' unit='dbus-org.freedesktop.Avahi.service'
Jan 18 22:04:30 derp dbus[438]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.Avahi.service': Unit dbus-org.freedesktop.Avahi.service failed to load: No such file or directory.
Jan 18 22:04:30 derp dbus-daemon[578]: Activating service name='ca.desrt.dconf'
Jan 18 22:04:30 derp dbus-daemon[578]: Successfully activated service 'ca.desrt.dconf'
Jan 18 22:04:30 derp systemd-coredump[761]: Process 655 (cinnamon) of user 1000 dumped core.

                                                   Stack trace of thread 655:
                                                   #0  0x00007f77f69025f8 raise (libc.so.6)
                                                   #1  0x00007f77f6903a7a abort (libc.so.6)
                                                   #2  0x00007f77f6eff8c5 g_assertion_message (libglib-2.0.so.0)
                                                   #3  0x00007f77f6eff95a g_assertion_message_expr (libglib-2.0.so.0)
                                                   #4  0x00007f77f3cb087e gtk_icon_info_load_icon_finish (libgtk-3.so.0)
                                                   #5  0x00007f77f3cb0908 n/a (libgtk-3.so.0)
                                                   #6  0x00007f77f7475413 n/a (libgio-2.0.so.0)
                                                   #7  0x00007f77f7475449 n/a (libgio-2.0.so.0)
                                                   #8  0x00007f77f6ed9c7a g_main_context_dispatch (libglib-2.0.so.0)
                                                   #9  0x00007f77f6eda020 n/a (libglib-2.0.so.0)
                                                   #10 0x00007f77f6eda342 g_main_loop_run (libglib-2.0.so.0)
                                                   #11 0x00007f77f82bd068 meta_run (libmuffin.so.0)
                                                   #12 0x00000000004017da main (cinnamon)
                                                   #13 0x00007f77f68ef610 __libc_start_main (libc.so.6)
                                                   #14 0x00000000004018b9 n/a (cinnamon)

                                                   Stack trace of thread 660:
                                                   #0  0x00007f77f6c8007f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f77edbf64b0 PR_WaitCondVar (libnspr4.so)
                                                   #2  0x00007f77f613e816 n/a (libmozjs-24.so)
                                                   #3  0x00007f77edbfbd7b n/a (libnspr4.so)
                                                   #4  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #5  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 659:
                                                   #0  0x00007f77f6c8007f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f77edbf64b0 PR_WaitCondVar (libnspr4.so)
                                                   #2  0x00007f77f60cae9e n/a (libmozjs-24.so)
                                                   #3  0x00007f77edbfbd7b n/a (libnspr4.so)
                                                   #4  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #5  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 657:
                                                   #0  0x00007f77f69af18d poll (libc.so.6)
                                                   #1  0x00007f77f6ed9fbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007f77f6eda342 g_main_loop_run (libglib-2.0.so.0)
                                                   #3  0x00007f77f74d0236 n/a (libgio-2.0.so.0)
                                                   #4  0x00007f77f6f00715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 658:
                                                   #0  0x00007f77f69af18d poll (libc.so.6)
                                                   #1  0x00007f77f6ed9fbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007f77f6eda0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f77e4b1525d n/a (libdconfsettings.so)
                                                   #4  0x00007f77f6f00715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 656:
                                                   #0  0x00007f77f69af18d poll (libc.so.6)
                                                   #1  0x00007f77f6ed9fbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007f77f6eda0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f77f6eda109 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f77f6f00715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 715:
                                                   #0  0x00007f77f69b3cf9 syscall (libc.so.6)
                                                   #1  0x00007f77f6f1e87a g_cond_wait_until (libglib-2.0.so.0)
                                                   #2  0x00007f77f6eaea69 n/a (libglib-2.0.so.0)
                                                   #3  0x00007f77f6f01086 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f77f6f00715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f77f69b813d __clone (libc.so.6)

                                                   Stack trace of thread 756:
                                                   #0  0x00007f77f69b3cf9 syscall (libc.so.6)
                                                   #1  0x00007f77f6f1e87a g_cond_wait_until (libglib-2.0.so.0)
                                                   #2  0x00007f77f6eaea69 n/a (libglib-2.0.so.0)
                                                   #3  0x00007f77f6f01086 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f77f6f00715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f77f6c7a4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f77f69b813d __clone (libc.so.6)
Jan 18 22:04:33 derp systemd-coredump[775]: Process 766 (cinnamon) of user 1000 dumped core.

                                                   Stack trace of thread 766:
                                                   #0  0x00007f7f9f1b55f8 raise (libc.so.6)
                                                   #1  0x00007f7f9f1b6a7a abort (libc.so.6)
                                                   #2  0x00007f7f9f7b28c5 g_assertion_message (libglib-2.0.so.0)
                                                   #3  0x00007f7f9f7b295a g_assertion_message_expr (libglib-2.0.so.0)
                                                   #4  0x00007f7f9c56387e gtk_icon_info_load_icon_finish (libgtk-3.so.0)
                                                   #5  0x00007f7f9c563908 n/a (libgtk-3.so.0)
                                                   #6  0x00007f7f9fd28413 n/a (libgio-2.0.so.0)
                                                   #7  0x00007f7f9fd28449 n/a (libgio-2.0.so.0)
                                                   #8  0x00007f7f9f78cc7a g_main_context_dispatch (libglib-2.0.so.0)
                                                   #9  0x00007f7f9f78d020 n/a (libglib-2.0.so.0)
                                                   #10 0x00007f7f9f78d342 g_main_loop_run (libglib-2.0.so.0)
                                                   #11 0x00007f7fa0b70068 meta_run (libmuffin.so.0)
                                                   #12 0x00000000004017da main (cinnamon)
                                                   #13 0x00007f7f9f1a2610 __libc_start_main (libc.so.6)
                                                   #14 0x00000000004018b9 n/a (cinnamon)

                                                   Stack trace of thread 768:
                                                   #0  0x00007f7f9f26218d poll (libc.so.6)
                                                   #1  0x00007f7f9fd19f29 g_socket_condition_check (libgio-2.0.so.0)
                                                   #2  0x00007f7f9fd836de n/a (libgio-2.0.so.0)
                                                   #3  0x00007f7f9fd85514 n/a (libgio-2.0.so.0)
                                                   #4  0x00007f7f9fd28413 n/a (libgio-2.0.so.0)
                                                   #5  0x00007f7f9fd28449 n/a (libgio-2.0.so.0)
                                                   #6  0x00007f7f9f78cc7a g_main_context_dispatch (libglib-2.0.so.0)
                                                   #7  0x00007f7f9f78d020 n/a (libglib-2.0.so.0)
                                                   #8  0x00007f7f9f78d342 g_main_loop_run (libglib-2.0.so.0)
                                                   #9  0x00007f7f9fd83236 n/a (libgio-2.0.so.0)
                                                   #10 0x00007f7f9f7b3715 n/a (libglib-2.0.so.0)
                                                   #11 0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #12 0x00007f7f9f26b13d __clone (libc.so.6)

                                                   Stack trace of thread 770:
                                                   #0  0x00007f7f9f53307f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f7f964a94b0 PR_WaitCondVar (libnspr4.so)
                                                   #2  0x00007f7f9e97de9e n/a (libmozjs-24.so)
                                                   #3  0x00007f7f964aed7b n/a (libnspr4.so)
                                                   #4  0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #5  0x00007f7f9f26b13d __clone (libc.so.6)

                                                   Stack trace of thread 773:
                                                   #0  0x00007f7f9f266cf9 syscall (libc.so.6)
                                                   #1  0x00007f7f9f7d187a g_cond_wait_until (libglib-2.0.so.0)
                                                   #2  0x00007f7f9f761a69 n/a (libglib-2.0.so.0)
                                                   #3  0x00007f7f9f7b4086 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f7f9f7b3715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f7f9f26b13d __clone (libc.so.6)

                                                   Stack trace of thread 771:
                                                   #0  0x00007f7f9f53307f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                   #1  0x00007f7f964a94b0 PR_WaitCondVar (libnspr4.so)
                                                   #2  0x00007f7f9e9f1816 n/a (libmozjs-24.so)
                                                   #3  0x00007f7f964aed7b n/a (libnspr4.so)
                                                   #4  0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #5  0x00007f7f9f26b13d __clone (libc.so.6)

                                                   Stack trace of thread 767:
                                                   #0  0x00007f7f9f26218d poll (libc.so.6)
                                                   #1  0x00007f7f9f78cfbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007f7f9f78d0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f7f9f78d109 n/a (libglib-2.0.so.0)
                                                   #4  0x00007f7f9f7b3715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f7f9f26b13d __clone (libc.so.6)

                                                   Stack trace of thread 769:
                                                   #0  0x00007f7f9f26218d poll (libc.so.6)
                                                   #1  0x00007f7f9f78cfbc n/a (libglib-2.0.so.0)
                                                   #2  0x00007f7f9f78d0cc g_main_context_iteration (libglib-2.0.so.0)
                                                   #3  0x00007f7f8d3c825d n/a (libdconfsettings.so)
                                                   #4  0x00007f7f9f7b3715 n/a (libglib-2.0.so.0)
                                                   #5  0x00007f7f9f52d4a4 start_thread (libpthread.so.0)
                                                   #6  0x00007f7f9f26b13d __clone (libc.so.6)
Jan 18 22:04:36 derp systemd[1]: Started Getty on tty2.

```

**Comment by mjenki03** [comment]
Try this.


 http://www.nvidia.com/download/driverResults.aspx/95159/en-us

**Comment by nathan-b** [comment]
For posterity:

I had this same problem. I don't believe this is an nvidia issue, it's an infinality / fontconfig issue.

Following this thread solved it for me: https://bbs.archlinux.org/viewtopic.php?id=221758
