### ISSUE TITLE
Network Applet showing too many wireless networks

### ISSUE THREAD

**Issue by notapantsday** [linuxmint/Cinnamon#5272]
I receive a lot of wireless networks from neighbors. The network manager applet is showing so many of them that I can't access the VPN settings, which are below the wireless networks. They're just pushed off screen. At the very bottom of the screen shot you can still see half of the word "Mehr..." which means "more..." as in "show me more networks" - sorry for the German.

As of now, I have to disable wi-fi, then reactivate it so I can access the VPN settings while my system is still busy searching for more networks.

I think there should be a maximum number of networks displayed in the applet, like 5 or 10. If you want to see more, you can still click on more/Mehr.

![screenshot](https://cloud.githubusercontent.com/assets/19206054/15043025/50e55894-12c9-11e6-9e1e-0ea280ca4c79.png)

**Comment by f2404** [comment]
What version are you using? It seems to have been resolved in Cinnamon 3 (see #3678).

**Comment by notapantsday** [comment]
I'm on 2.6.11. I'll try to update to Cinnamon 3 and see if it works. Thanks!

**Comment by JosephMcc** [comment]
Closing since it's been 3 months since getting any more response. Don't know if this is still an issue in Cinnamon3

**Comment by bencromwell** [comment]
This is still an issue in 3.2.7 / Linux Mint 18.1:

```
 $ apt policy cinnamon
cinnamon:
  Installed: 3.2.7+serena
  Candidate: 3.2.7+serena
```

![cinnamon-wifi-networks](https://cloud.githubusercontent.com/assets/683855/25906227/ed22b30a-359b-11e7-93a4-8a8a1d1491e3.png)

Unable to get to the VPNs in order to switch them.
