### ISSUE TITLE
[keyboard applet] uses wrong flag

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/Cinnamon#5347]
If you add "Russian (phonetic for germans)" as second language, the keyboard applet uses the german flag in the panel. It should use the russian flag, because it is meant to type russian letters.

**Comment by andyn** [comment]
The keyboard applet is currently using "group name" instead of "short name" when it determines the flag icon to be used. Would the correct behaviour be to prioritize the short name and fall back to the group name, should the correct flag not be found?

I've fixed this in my local install but I'm not submitting patches/pull requests until I can ensure it works properly with other layout combinations.

**Comment by NikoKrause** [comment]
This bug still exists as I described here: https://github.com/linuxmint/Cinnamon/commit/b9344bb9829a3a2e8d886e60eda7d6dd64360a53

Is it possible to reopen this issue?

**Comment by JosephMcc** [comment]
Sure thing.

**Comment by NikoKrause** [comment]
See explanation of mtwebster https://github.com/linuxmint/Cinnamon/commit/b9344bb9829a3a2e8d886e60eda7d6dd64360a53
