### ISSUE TITLE
[LM18] Taskbar disapears if KODI is started on a second display

### ISSUE THREAD

**Issue by bitboy85** [linuxmint/Cinnamon#5460]
After Upgrading from LM17.3 to 18 Cinnamon i noticed that the taskbar disappears when kodi is running on a second display.
This Behaviour also happend in 17.3 but is was possible to restore the taskbar with clicking on the desktop. in LM18 this isn't working anymore and the taskbar is gone until kodi is closed.
Kodi is installed from the team-xbmc ppa not from official repositories.

**Comment by bitboy85** [comment]
There is a similar description from Ricardo Almeida  at http://segfault.linuxmint.com/2016/04/cinnamon-3-0-released/ I also use nvidia proprietary drivers

**Comment by fritsch** [comment]
Btw. do you use kodi in fullscreen mode? If yes, we disable all compositors. If you want a proper second display behaviour, press \ button and use kodi windowed.

**Comment by bitboy85** [comment]
your right, i'm using Kodi in fullscreen mode. It seems to work using window mode but the window frame doesn't look that good :( I just found out that the same happens using vlc, but only if it is started in fullscreen mode. If you select window mode with vlc and after that choose fullscreen its working. Switching between modes with kodi doesn't help

**Comment by fritsch** [comment]
As said before: fix the root cause, please.

**Comment by TheDevKing** [comment]
Here's a workaround that requires the creation of 2 files:

`~/.kodi/userdata/keymaps/fullscreen.xml` where `USER`, put your user
```
<keymap>
  <global>
    <keyboard>
      <backslash>RunScript(/home/USER/.kodi/scripts/toggleFullscreen.py)</backslash>
      <backslash mod="ctrl">ToggleFullScreen</backslash>
    </keyboard>
  </global>
</keymap>
```

`~/.kodi/scripts/toggleFullscreen.py` set to executable with `chmod +x toggleFullscreen.py`
```
import os
os.system('wmctrl -r :ACTIVE: -b toggle,fullscreen')
```

What this does is remap \ to toggle a fullscreen state of the currently active window (which should necessarily be Kodi) though wmctrl rather than through Kodi. The default Kodi fullscreen action can now be toggled with ctrl + \

Hope that helps somebody

**Comment by bitboy85** [comment]
Just tried LM 18.2 Beta Cinnamon on a T420. Its even worse now. No matter if you have window mode or full Screen, as soon as you select the other Display within kodi, it Switches, but the second screen keeps black. If you Switch it back, the Primary Screen is also black.

**Comment by Huecuva** [comment]
TheDevKing: your workaround did not work for me.

**Comment by mtwebster** [comment]
We just did a bit of work on how panels behave during fullscreen window mode.  And I just did a bit of testing with Kodi.

What I see with the new Cinnamon release (3.8) and multiple monitors -  

At startup, Kodi appears to make itself larger than the monitor it's supposed to be fullscreened on.  I see a vertical strip of a window in the adjacent monitor next to the monitor with kodi fullscreen.

This confuses muffin into thinking both monitors are fullscreen, and hides the panels.  Now, selecting any other window (or the desktop) besides kodi, will bring back the panels on the monitor Kodi is not on, though the strip of window is still visible on this monitor.

Through various means (including this workaround mentioned, toggling fullscreen) Kodi will finally correct itself, occupy only *exactly* the monitor it's on, and panels will behave properly.  Another way to fix this without setting up that workaround, is you can attempt to drag the kodi window via <alt>-dragging the Kodi window.  It won't actually move, but unfocusing and re-focusing will cause it to essentially fix itself.

I'm not sure what this extra bit of window is.  It doesn't match up with what you see on the other monitor.  But you can run xprop on it, and see that it is indeed Kodi.

I've never seen this behavior on any other programs, and the fact that it corrects itself leads me to believe that it's not really a Cinnamon/Muffin bug, though perhaps something about muffin's behavior causes the issue to manifest this way.  I'm not sure.  I do see requests by the application to the window manager to position itself in the wrong place.  Maybe other WMs ignore non-sensical requests (like a fullscreen window trying to size itself larger than a single monitor?)

To reiterate, we've just recently improved a few things regarding panel behavior, and what I'm describing is this new behavior.  In a nutshell, previously, any monitor that had a full screen window on it would have its panels hidden, *regardless of whether that window was focused or on top of other windows on that monitor.*  This has been changed so that the panels only disappear when the fullscreen window is not obscured by any other windows.  Additionally, alt-tabbing or opening the cinnamon menu will bring back panels in a more appropriate manner, depending on what monitor contains the user's focus at the time.

I can look more into how muffin treats this Kodo window, but I hesitate to force behavior or constraints on any given application, especially as workarounds - perhaps there are other possibly related Kodi issues that might shed some light on this.

**Comment by mtwebster** [comment]
I just pushed a change to muffin, which will ignore this extra bit of the Kodi window bleeding over into the next monitor.  This will in turn prevent the panels from disappearing on that other monitor.

I still think there may be an issue with Kodi trying to size itself larger than the monitor, but I don't have any data nor time to look into it further for now.  This should make things more than tolerable, with the additional panel fixes in Cinnamon and muffin.

**Comment by Huecuva** [comment]
So if Kodi is trying to make itself bigger than the screen it's expanded on, doesn't that make it a Kodi problem? But then why is it only happening in Cinnamon?

Just now, it seems as if perhaps the workaround finally took effect or something else has occurred because now I am able to full-screen Kodi on my secondary display without losing my taskbar. However, what's worse now is that full-screen Kodi no longer prevents the screensaver from kicking in. I had to unlock my machine twice during a TV show.

**Comment by Huecuva** [comment]
So when are these fixes going to be pushed to release?

**Comment by Huecuva** [comment]
Hello?

**Comment by Huecuva** [comment]
I still haven't seen anything like this mentioned in the updates for Linux Mint 18.3 Cinnamon and I'm still having the problem. Is there any news?

**Comment by mtwebster** [comment]
It's fixed in Cinnamon 3.8.* - you'll need to upgrade to mint 19, it won't be backported to 18.3

**Comment by fritsch** [comment]
@mtwebster is this was such a long stand bug, could you link the commit that fixed it? Highly interested!

**Comment by mtwebster** [comment]
This commit was the only one really specific to the kodi issue: https://github.com/linuxmint/muffin/commit/23cd1c54503eb7a12b39686c5a312245e7801c8c

There were actually quite a few commits to muffin and cinnamon during this past dev cycle to address a lot of different, annoying fullscreen behavior issues. (along with fixes to things we broke by our initial fixes :))

A few more commits are linked here: https://github.com/linuxmint/muffin/pull/317.

There are more related minor fixes in muffin, all of it to attempt to make fullscreen windows and panels behave a bit more sanely, in various single- and multi-monitor situations.

**Comment by fritsch** [comment]
Thanks!

**Comment by Huecuva** [comment]
I was unaware that Mint 19 had been released. It just so happens I was going to upgrade my HTPC to a Q6600 and reintsall mint today anyway, now I can upgrade to 19. Excellent!

**Comment by Huecuva** [comment]
I upgraded to Linux Mint 19 and it's all working properly now. I'm glad to see that this is finally sorted out.
