### ISSUE TITLE
Screen Lock reorders windows to hardware primary display in dual screen on returning

### ISSUE THREAD

**Issue by grizzlyfred** [linuxmint/cinnamon#5487]
I have a FHD and a 4K Monitor connected to an NVIDA-proprietary driven card.
FHD ist connected with DVI and 4K is connected with Display Port.
From the BIOS point of view, the FHD Display is the primary display, but I set the 4K display within Cinnamon 3 and within NVDIA settings as the primary display.

In both Mint 18 and Manjaro-Cinnamon, after the screen saver / lock has been activated and then I return to my session by re-entering the password, open windows are moved from the 4K ("virtual primary") desktop to the FHD ("virtual secondary") desktop.

I expected to find all windows at their original place - as is the case with long-used Mint 17.3.

**Comment by mtwebster** [comment]
Is happening when the screen is just locked, or after maybe waking from suspend?  (if you lock the screen, then immediately unlock it, does it happen?)  I just want to be as clear as possible about the condition where it occurs.

**Comment by Feuerfuchs** [comment]
I have a similar setup (4K display over DisplayPort + FHD display over HDMI) and I think I know what the reason for this problem is.

When I started using my 4K display, I had the same issue that all windows were all on my primary display when my computer was idle for a while and the displays were put into the standby mode. It turned out my 4K display stopped reporting as being connected as soon as it entered the standby mode, and when it woke up it was recognized again. Since Cinnamon automatically adapts to new display layouts and the 4K display was gone at one point, it moved all windows to the remaining display, and when the 4K display woke up, Cinnamon recognized it as the primary one and just moved all the contents from the FHD display to the 4K display.

So to me this doesn't look like an issue with Cinnamon — it just does what it's supposed to do when the display layout changes.

You can circumvent the issue by disabling Cinnamon's automatic adaption altogether:
`dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false`

**Comment by grizzlyfred** [comment]
I try to sum up what I found out (untested yet, but now obvious - afraid to log out to have to setup all again.

@mtwebster It happens always - explanation below
@Feuerfuchs: On Mint 17.3 there were no problems at all

But I think the flaw was as follows - also refer [http://askubuntu.com/questions/379483/nvidia-x-server-settings-lost-on-every-reboot](url)

- The NVIDIA graphical screen configuration panel is by design not persistent. You have to save the machine-wide configuration in the "X Server Display Configuration" dialogue and the per-user settings in the nvidia-settings Configuration dialogue, but it is not obvious which option belongs to which domain.
- Mint Cinnamon has its own configuration App called "Monitors" (or Displays?) in the start menu (and the system configuration control center). Here you have to change something to release the "Apply" button. Then a ~/.config/monitors.xml is saved. As I did my install in a Virtualbox with direct acces to the disk to stay on 17.3 for a while until 18 had a usable base config for me (apps and finetunings) this file was obviously totally wrong in the first place.
I will now check if after saving a new monitors.xml which looks promising, all will be good.
I had to tinker with "nomodeset" in the grub line though and have not yet figured out how to get a "normal" bootup-message (like whats started instead of the splash screen...)

**Comment by grizzlyfred** [comment]
Tested now the followind:
- Lock screen and re-login => all good
- Log out and re-login => small flaw, mouse cursor and the like are now slightly (60% smaller) than before

So I figure there is a "usability" issue as NVIDIA proprieatary driver settings and cinnamon built-in config is not synchronised (compare to windows, where you usually have vendor-specific tabs added to the display config (not sure for 10 though).
Will this ever fix or is it rather a matter of documentation / learning curve? Kind of unsure whether to close this or not...

**Comment by grizzlyfred** [comment]
Mostly works stable after some days of testing. Seldomly the login screen is back to the FHD secondary disply, but fortunately no windows are reordered.

**Comment by pwil3058** [comment]
I've just suddenly (today) noticed this behaviour on my system.  Relevant details are:

- Cinnamon-3.0.2 updated on 11OCT2016 (over 6 weeks ago)
- only desktop setting changes that I've made recently is using "click to focus" instead of "focus follows mouse"
- most recent "likely" significant change was kernel upgrade to 4.8.7 yesterday from 4.8.6

I'm going to reboot with an older kernel to see if the problem goes away.

**Comment by pwil3058** [comment]
After rebooting with the older kernel (4.8.6-201), the problem has not been seen.  This would indicate that a change to the graphics driver in kernel-4.8.7 is strongly implicated in this problem. From Cinnamon's "System Info" page, my graphics hardware is:

AMD/ATI Cape Verde XT [Radeon HD 7770/8760/R7 250X]](prog-if 00 [VGA controller])

Is there any other information I can provide that would be of help?

**Comment by pwil3058** [comment]
I've just upgraded to kernel-4.8.8 and the problem seems (only a few minutes running, though) to have gone away.  If it comes back I'll report it again.

**Comment by pwil3058** [comment]
It's back but there is a twist.  When I tested by locking/unlocking the screen it didn't occur but when I left the machine unused for a while and it turned off the screens (without locking) the problem occurred again.  This is with the 4.8.8 kernel.  I'm going to switch back to 4.8.6.

**Comment by pwil3058** [comment]
It seems to be the case that Cinnamon isn't turning the monitors off when I'm using 4.8.6 kernel (just locking them) which could be why the problem doesn't occur there.

**Comment by pwil3058** [comment]
After another half day unattended with kernel 4.8.6 Cinnamon still hasn't turned the screens off but locking the screens doesn't cause the moving windows problem.  So both 4.8.6 and 4.8.7/8 are causing problems for Cinnamon albeit different ones.

**Comment by pwil3058** [comment]
Went to kernel-4.8.8 and did:

dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false

which fixed the problem of the migrating windows.  However, a new problem has arisen in that after the system comes back from "monitors off" the sound (which comes via the video card) no longer works.

Cinnamon can see the sound driver in the "settings" tool and it is selected as sound system to be used but nothing comes out of the speakers.  Tried kernel 4.8.7 and same problem.  Problem does not exist with kernel 4.8.6 but with that kernel Cinnamon seems unable to turn the monitors off.

**Comment by germanfr** [comment]
I've installed a second monitor just today and this has been happening to me all the day.

I've been out and when I came back and resumed my computer all windows where moved to the secondary monitor. Also, new windows opened in there, even though they where launched from the primary one and the mouse was there. 

Now I lock it and nothing happens. I suspend it and nothing happens. I even let it turn off the screen by the power timeout but nothing. I can't reproduce anything again.

**Comment by tjmpoc** [comment]
I too see the bug "uncommanded move of all windows to a single monitor on a two monitor setup".

OS: Linux mint 18.1 with kernel-4.4.0-53
hardware: Intel i7-6700 integrated GPU and dual identical external monitors

the bug only happens after leaving the computer (e.g. for 10 minutes) but seems to be intermittent.  I have tried disabling as many screensaver and suspend settings as I could find, but without effecting the bug.

**Comment by tjmpoc** [comment]
make that "Linux Mint Cinnamon 18.1".
also, I don't know if it is related, but I too see the "Cinnamon unable to turn off monitors" bug.

**Comment by AlbertJP** [comment]
Bug still exists in 18.1. At my work I currently use three monitors: laptop and two external screens (DP and HDMI). The windows on the HDMI monitor get moved to the laptop screen, but the windows on the DP monitor stay in place. Intel HD Graphics 620.

**Comment by finswimmer** [comment]
Hello,
are there any new news to this problem? 

I'm using cinnamon 3.6 under ArchLinux. My Laptop have an intel card for the internal display and a nvidia card for the externals.

This workaround doesn't work for me:
`dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false`

It seems that cinnamon is just to fast in recognizing all monitors. So if the external monitor needs to long to wake up, the described behaviour appears.

fin swimmer

**Comment by grizzlyfred** [comment]
Unfortunately, I had to switch to single monitor setup for now (old one broken) so I cannot update. As soon as dualhead is on the table again, I'll keep you posted.
For some reason, however, I did not observe that behaviour on debian stretch with an hp ultraportable 11" thing

**Comment by macrokernel** [comment]
I am using Ubuntu Trusty with Cinnamon 2.8.8. My computer has an Intel i3-3220 video with a TV on HDMI3 and a monitor on DP1, both are Full HD, monitor is primary screen. 

This workaround does work for me:
`dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false`

**Comment by redjaguar** [comment]
4K monitor on HDMI, 2K monitor on DVI. Mint 17.3 did not have this issue. 18.1 does. 17.3 has the "windows being moved to single display instead of saved in location" when the 4K is turned off.

My workaround: keep the nvidia-settings application running... however I still have to rearrange the windows back to where they were.

I have the settings saved in both the user and system wide X settings but that does not make a difference.

**Comment by bitstrings** [comment]
I have tried dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false but it doesn't fix anything, Cinnamon 18 and 19.

This is super annoying.

**Comment by redjaguar** [comment]
This may be a separate but related bug but now instead of jus re-ordering
the windows the display mode goes to mirrored when the displays are powered
off then turned back on. Don't know which is more annoying.

**Comment by mtwebster** [comment]
Disable it in startup programs - 
![image](https://user-images.githubusercontent.com/262776/42482143-2ea28960-83b4-11e8-8ea2-e11b81c2545c.png)

**Comment by bitstrings** [comment]
Yeah that's not going to work for all, specially if you need to rotate or position your screens (nvidia-settings might help). However, you have 2 choices. Either use another xrandr client like lxrandr or simply edit cinnamon-settings-daemon-xrandr.desktop (.config/autostart) and add **--exit-time**:

`Exec=/usr/lib/cinnamon-settings-daemon/csd-xrandr --exit-time`

**Comment by nicoulaj** [comment]
I have also been affected by this bug for many versions. It happens when screens wake up (no suspend needed, just screens off). I guess this is due to the main screen being slower at waking up than the other one, and cinnamon does not wait long enough. If this work with a timeout, maybe just make it somehow configurable ?

Some info:

- Distro: Arch Linux
- Cinnamon 3.8.8
- Using nvidia proprietary driver 396.54
- Screen models: Asus PG2789QR / Asus VG248QE
- Xorg config:

       Section "ServerLayout"
           Identifier     "Layout0"
           Screen      0  "Screen0" 0 0
           InputDevice    "Keyboard0" "CoreKeyboard"
           InputDevice    "Mouse0" "CorePointer"
           Option         "Xinerama" "0"
       EndSection
       
       Section "Files"
       EndSection
       
       Section "InputDevice"
           Identifier     "Mouse0"
           Driver         "mouse"
           Option         "Protocol" "auto"
           Option         "Device" "/dev/psaux"
           Option         "Emulate3Buttons" "no"
           Option         "ZAxisMapping" "4 5"
       EndSection
       
       Section "InputDevice"
           Identifier     "Keyboard0"
           Driver         "kbd"
       EndSection
       
       Section "Monitor"
           Identifier     "Monitor0"
           VendorName     "Unknown"
           ModelName      "Ancor Communications Inc VG248"
           HorizSync       30.0 - 160.0
           VertRefresh     50.0 - 150.0
           Option         "DPMS"
       EndSection
       
       Section "Device"
           Identifier     "Device0"
           Driver         "nvidia"
           VendorName     "NVIDIA Corporation"
           BoardName      "GeForce GTX 1080 Ti"
       EndSection
       
       Section "Screen"
           Identifier     "Screen0"
           Device         "Device0"
           Monitor        "Monitor0"
           DefaultDepth    24
           Option         "Stereo" "0"
           Option         "nvidiaXineramaInfoOrder" "DFP-5"
           Option         "metamodes" "DP-0: 1920x1080_144 +2560+360 {AllowGSYNC=Off}, DP-2: 2560x1440_144 +0+0 {AllowGSYNC=Off}"
           Option         "SLI" "Off"
           Option         "MultiGPU" "Off"
           Option         "BaseMosaic" "off"
           SubSection     "Display"
               Depth       24
           EndSubSection
       EndSection

- `~/.config/monitors.xml`:

       <monitors version="1">
         <configuration>
             <clone>no</clone>
             <output name="DP-2">
                 <vendor>AUS</vendor>
                 <product>0x27b1</product>
                 <serial>0x0001747a</serial>
                 <width>2560</width>
                 <height>1440</height>
                 <rate>144</rate>
                 <x>0</x>
                 <y>0</y>
                 <rotation>normal</rotation>
                 <reflect_x>no</reflect_x>
                 <reflect_y>no</reflect_y>
                 <primary>yes</primary>
             </output>
             <output name="DP-0">
                 <vendor>ACI</vendor>
                 <product>0x24a4</product>
                 <serial>0x01010101</serial>
                 <width>1920</width>
                 <height>1080</height>
                 <rate>144</rate>
                 <x>2560</x>
                 <y>360</y>
                 <rotation>normal</rotation>
                 <reflect_x>no</reflect_x>
                 <reflect_y>no</reflect_y>
                 <primary>no</primary>
             </output>
         </configuration>
       </monitors>

**Comment by grizzlyfred** [comment]
Actually, it seems to me like a more widespread problem now in 2018, because I have seen the same happening on android devices (revealing what the user sees for a short time before asking e.g. the swipe code.
My current mankato vm on my mac, however seems to correctly "blacken" everything when going in lock mode - so as said above, there is probably two things at work - not waiting a reasonable time for multiple monitors to wake up AND not blacking the user screen prior to locking...

**Comment by torgash-ivanblch** [comment]
Hey everyone. Still no solution? This bug irritates me even in Cinnamon 4 of Linux Mint 19.1. 
Secondary display is where windows gather on wake up

**Comment by brigantino2** [comment]
I have the same problem on Linux Mint 19.1 with two monitors. I found a workaround on another blog. It looks like the problem comes with power management: when DPMS is active monitors are turned off after a period of inactivity. In this case the system thinks there is no monitor plugged and when reactivating, windows move to the first screen that powers on (I suppose).
So the workaround is disabling this PM feature. In Mint menu, Power Management -> set "Turn off screen when inactive" to "never".

**Comment by IAMtheIAM** [comment]
Years later it still occurs! Mint 17, 18, and 19. Really annoying

**Comment by socketbox** [comment]
Still an issue under 19.2, with kernel 4.15.0-58-generic x86_64

**Comment by tdenewiler** [comment]
I have been having a similar problem for a year or so. I have dual monitors: FHD as primary on HDMI and 4K as secondary on Display Port. I let the monitors sleep after about 10 minutes. When waking up, all windows move from secondary to primary monitor. Both monitors are plugged into an nVidida GeForce GTX 1080.

Today I accidentally fixed the issue for my setup. My secondary 4K monitor is a Samsung, Model Code LU28E510DS/ZA, Version PA01. I went into the settings on the monitor (not through the OS) and changed `Samsung Magic Bright` from `Standard` to `Custom`. I also turned `Eye Saver Mode` from `On` to `Off`. After making those changes the monitors went to sleep after 10 minutes, woke up on mouse movement, and all of my windows were on the monitors I had previously moved them to.

I had previously tried the following suggestion without success (reverted the setting after it didn't make any difference):

     dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false

My operating system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
```

The kernel I am using is

```
$ uname -a
Linux leaf 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I hope that helps someone.

**Comment by Gustav0ar** [comment]
I'm having this issue, it is really annoying. In my setup I have workspaces enabled only in main monitor.
I'm using Linux Mint 19.3, 
Kernel: 5.3.0-24-generic #26~18.04.2-Ubuntu
QHD Acer monitor using Display Port and
FHD LG monitor using HDMI
GPU: Nvidia GTX 1070 using official nvidia 440.44 driver

The DisplayPort monitor is set as primary, but the windows are all moved to the HDMI one when computer wakes up.

**Comment by evanleonard** [comment]
Having this issue now again. System info:

GPU: NVIDIA Corporation GM107GL [Quadro K1200]
Nvidia driver version: 430.50
Distributor ID:	
Debian Description:	Debian GNU/Linux rodete
Release:	rodete 
Codename:	rodete
5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux





Dual monitors, and the newer 4k monitor seems to take longer to wake up than the older 27" monitor, so all windows go to the older 27" monitor (which is the secondary monitor).

**Comment by deeaycee** [comment]
Happening to me too. for a few years.... i'm on the newest mint and the newest cinnnamon. two identical samsung monitors. one on hdmi, one on display port. both on nvidia card.

`$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
`

**Comment by jorp** [comment]
Just to chime in here, it looks like this issue possibly spans DEs as well. I'm experiencing something similar with a triple monitor setup on Fedora 31, Xfce 4.14. 

It is possible that this is an Xorg bug?

[Here](https://bugs.launchpad.net/ubuntu/+source/kscreen/+bug/1573345?comments=all) is what seems to be a relevant report for KDE on Ubuntu.

I've also found a [Xfce forum post](https://forum.xfce.org/viewtopic.php?pid=56538) that seems to be related as well.

**Comment by LamaRaz** [comment]
I have this 4 year old problem on wayland too (had it on xorg before that).

The solution seems to be to just switch to a WM (i3, sway, etc).

**Comment by mintyDave7s** [comment]
Just to be different, this is an issue for me on Mint 19.3 Mate simply by *plugging in* an HDMI cable connected to a powered off ASUS 27" external monitor.
Dell Studio 1555, dell (maybe radeon?) graphics, not nVidia.
My laptop monitor is set as primary, but as soon as I plug in the HDMI cable, all my windows (and desktop icons like "Computer" and mounted filesystems) *move* to the powered-off external monitor.
The arrangement is such that the external monitor becomes 0,0 on the screen (is it display or screen?) with the primary laptop screen to the right.
I could maybe understand moving windows when the external display is turned on, but why are they moving when it is off and the HDMI cable is plugged in?!

**Comment by brianread108** [comment]
This is also an issue for me on Fedora 32 with Cinnamon. Just changed my graphics card to Radeon 550, attached to two monitors by DVI and HDMI and this is occurring when I suspend the system (which I do a lot - anything from 5-10 times a day), all the windows are then concentrated on one of the screens (the designated "primary"), when I unsuspend. It did not happen with my previous graphics card (Radeon R7) connected by VGA and DVI to the monitors. I presume the new card is detecting the turn off and reporting back, causing Cinnamon/Mutter(?) to adjust the displays. I really "just" need some way of suppressing that activity in whatever is doing it!  If sopmeone could point me in the right direction I could have a look at the source, but I need some initial direction.

**Comment by bes1002t** [comment]
Same issue here with Fedora 31 and Cinnamon.

My setup is 2 QHD monitors connected via mini display port daisy chain

**Comment by beedogs** [comment]
how has this bug, which has persisted across several versions of Mint, and which appears to be very frustratingly widespread, lingered for FOUR YEARS without even anyone being assigned to the issue?

Come on.

**Comment by janvlug** [comment]
See also:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1419
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2092
https://bugs.launchpad.net/gnome-shell/+bug/1295267
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/380
https://bugzilla.redhat.com/show_bug.cgi?id=1878367

**Comment by cems2** [comment]
I tried the suggestion of @Bitstrings above as so far it's working.  At least through the first several suspend tests.  
So far the following fixed the problem I was seeing.

I did this.  Edit this file /etc/xdg/autostart/cinnamon-settings-daemon-xrandr.desktop 
and alter the line
Exec=/usr/lib/cinnamon-settings-daemon/csd-xrandr
to
Exec=/usr/lib/cinnamon-settings-daemon/csd-xrandr --exit-time 1

I suspect that what may possibly matter here is that there are two things going on that happen at different times.  I suspect that there is a sleep issue-- one monitor may turn off later than the other after video signal shuts off.  And then there may be a wake time lag in the monitors responding to the video card.  It may be that this command fixes the first of these.  I wonder if there is a related command that might look like  --enter-time 1  ???

**Comment by bes1002t** [comment]
@cem2 unfortunately setting "Exec=/usr/lib/cinnamon-settings-daemon/csd-xrandr --exit-time 1" will kill my session. If my screen goes to sleep, there is no way to wake it up again. I had to force poweroff my machine and boot again. After removing "--exit-time 1" screen wakeup works again as expected.

OS: Fedora 32

**Comment by franklx** [comment]
@cems2 your solution worked for me.
I'm running mint 20.1 beta (I had the same issue even on mint 20).

**Comment by franklx** [comment]
Before the ```csd-xrandr``` modification display sleep didn't work (I had to use ```xset dpms force off``` to force monitors enter sleep mode), now even this problem is fixed and sleep works as expected.
I don't know how these issues are related...

**Comment by FStefanni** [comment]
Hi,

I have the same issue, I am using Debian testing (bookworm).
I'll try the proposed workarounds, but it seems to me that the actual solution should be something "out of the box".
So I am not sure the proposed workaround is 100% correct: as @bes1002t wrote (but also the note by @franklx), it could lead to unexpected behaviors... I hope the cinnamon team will fix this issue asap.

Regards

**Comment by FeralBytes** [comment]
Seems that #5619 is related.

**Comment by HighOnVoltage** [comment]
@FStefanni 
I can also confirm it's an issue with Debian (11) Bullseye

**Comment by FStefanni** [comment]
Hi,

yes, #5619 is related for sure. I still do not think that making a daemon to exit is good, since we are going to loose its functionalities...

Since it affects different versions of Debian, I am wondering if it is a cinnamon component bug, or of a third-party software.
For example, I am wondering if other DE have the same issue... If I'll try, I'll let you know.

Even if this is not a critical functionality bug, this is very annoying and haveily damages the usability and the user experience.

Regards

**Comment by FeralBytes** [comment]
From this issue: https://github.com/linuxmint/cinnamon/issues/5477
I found this script: https://github.com/dosmanak/wmsavior
I am going to give it a try and will report back, because currently this is really starting to annoy me. If a simple state script can solve the issue then it probably is what we should implement in cinnamon to fix it.

**Comment by FeralBytes** [comment]
Adding "--exit-time=5" to xrandr in the startup applications seems to have fixed the issue for now.

**Comment by brianread108** [comment]
Update on my problem 'with Fedora 37.  Actually the problem seem to be now that tasks left on the 2nd Workspace end up on the 1st workspace after a suspend. This may well be a seperate bug?

**Comment by giafitano-ux** [comment]
# Fix Monitor Configuration Reset After Hibernate on Debian Trixie (Cinnamon Desktop)

When a Cinnamon desktop system wakes from hibernation, the monitor configuration can reset to a default layout, losing any custom arrangement set in Display Settings. This appears to be caused by the display server losing monitor EDID data during hibernation and re-detecting the monitors on wake, triggering auto-configuration.

The following is a workaround that uses a systemd sleep hook to restore the correct monitor layout automatically after every hibernate or hybrid-sleep cycle. This was tested on Debian Trixie with a Cinnamon desktop and three monitors connected to an NVIDIA RTX 3080 Ti via DisplayPort, but should work on any X11-based Cinnamon setup.

## Step 1: Identify Your Monitors

From the terminal, run:
```bash
xrandr --query
```

This outputs multiple lines per monitor. Look for lines beginning with `HDMI-# connected` or `DP-# connected`:
```
Screen 0: minimum 320 x 200, current 7280 x 1440, maximum 16384 x 16384
DP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm  <-- This line
   1920x1080     71.91*+  59.96    60.00    59.94    59.93
   1680x1050     59.95    59.88
   1400x1050     59.98
   1600x900      59.94    59.95    60.00    59.82
   ... remaining lines truncated ...
```

In this example, all three monitors use DisplayPort, shown as `DP-1`, `DP-2`, and `DP-3`. If your monitors use HDMI, replace `DP` with `HDMI` throughout.

## Step 2: Note Your Monitor Configuration

From the `xrandr` output, find the connected monitors (non-relevant lines removed):
```
DP-1 connected 1920x1080+0+0
DP-2 connected 1920x1080+5360+0
DP-3 connected primary 3440x1440+1920+0
```

The format is: `PORT MODE+XPOSITION+YPOSITION`

Breaking that down:

| Port | Resolution | Position |
|------|------------|----------|
| DP-1 | 1920x1080  | 0+0      |
| DP-2 | 1920x1080  | 5360+0   |
| DP-3 | 3440x1440  | 1920+0   |

In this example the physical monitor layout from left to right is:
```
DP-1    DP-3 (primary)    DP-2
```

This translates to the following xrandr arguments:
```
DP-1 --mode 1920x1080 --pos 0x0
DP-3 --mode 3440x1440 --pos 1920x0 --primary
DP-2 --mode 1920x1080 --pos 5360x0
```

## Step 3: Create the System Sleep Directory

The directory may not exist by default. Create it with:
```bash
sudo mkdir -p /lib/systemd/system-sleep
```

## Step 4: Create the Script
```bash
sudo nano /lib/systemd/system-sleep/fix-monitors.sh
```

Add the following, editing the `xrandr` section to match your configuration. Replace `jim` with your username:
```bash
#!/bin/bash
if [ "$1" = "post" ] || [ "$2" = "hibernate" ] || [ "$2" = "hybrid-sleep" ]; then
    sleep 6
    export DISPLAY=:0
    export XAUTHORITY=/home/jim/.Xauthority
    xrandr --output DP-1 --mode 1920x1080 --pos 0x0 \
           --output DP-3 --mode 3440x1440 --pos 1920x0 --primary \
           --output DP-2 --mode 1920x1080 --pos 5360x0
fi
```

Save with `Ctrl+O`, then exit with `Ctrl+X`.

## Step 5: Make the Script Executable
```bash
sudo chmod +x /lib/systemd/system-sleep/fix-monitors.sh
```

## Step 6: Test

First, test the script manually to confirm your monitors arrange correctly:
```bash
sudo /lib/systemd/system-sleep/fix-monitors.sh post suspend
```

Your monitors should briefly flicker and settle into the correct layout. Then test with a real hibernate cycle:
```bash
systemctl hibernate
```

Wake the machine and verify the monitor layout is correct.

## Notes

- If the layout still resets after hibernate, try increasing the `sleep 6` delay to `sleep 10` or higher. Hibernation can take longer to restore depending on how much RAM is in use.
- The `sleep` directory at `/lib/systemd/system-sleep/` is automatically scanned by systemd — no additional registration of the script is needed.
