### ISSUE TITLE
Cinnamon segfaulting on fullscreen apps

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/Cinnamon#5564]
>[23888.830032] cinnamon[3032]: segfault at 18 ip 00007f0525dae680 sp 00007fffe84a2c98 error 4 in libmuffin.so.0.0.0[7f0525d4f000+b9000]
[23891.387410] cinnamon[7228]: segfault at 0 ip 00007f2eedf5b549 sp 00007fff74f57820 error 4 in libcogl.so.20.4.1[7f2eedf2a000+b2000]
[23892.618286] cinnamon[7245]: segfault at 0 ip 00007fa2f3019549 sp 00007ffca7e6a450 error 4 in libcogl.so.20.4.1[7fa2f2fe8000+b2000]
[26330.633050] cinnamon[7948]: segfault at 18 ip 00007f821622d680 sp 00007ffc85dd6ed8 error 4 in libmuffin.so.0.0.0[7f82161ce000+b9000]

That is from dmesg. This most commonly happens in PCSX2, and sometimes also happens when I alt+tab, it tells me cinnamon has crashed and whether I would like to restart. I am on nvidia-367 drivers (happens on the intel gpu too) and using cinnamon 3.0.7.

This also happens with apps like mpv (though it hasn't happened to me recently) and it has also happened while exiting some steam games.

**Comment by JosephMcc** [comment]
This should already be fixed in git master. Another pertinent issue: https://github.com/linuxmint/muffin/issues/249

**Comment by SethDusek** [comment]
@JosephMCC is there any ppa to get this latest Cinnamon? Or do I have to build from git myself?

**Comment by JosephMcc** [comment]
On Mint you can run the nightly builds ppa. Be aware though that upgrades the whole cinnamon stack which is under a lot of dev right now.

**Comment by JosephMcc** [comment]
I would actually hold off a bit. We can see if we can get that particular fix out to cinnamon 3.0 users.

**Comment by SethDusek** [comment]
@JosephMcc Any update on when this will be in mint 18 repos? Some apps still crash cinnamon for me
