### ISSUE TITLE
Cinnamon 3.8 crashes after reboot

### ISSUE THREAD

**Issue by Steffen1989** [linuxmint/Cinnamon#7522]
```
Cinnamon 3.8.0-1 
Arch Linux
Intel HD Graphics 3000
Lenovo Edge 330 Laptop 
 ```

**Issue**
Since the upgrade from Cinnamon 3.6.7-3, I often experience a crash of Cinnamon after logging in.
When I confirm to restart Cinnamon after it has crashed, everything seems to work properly.
Note that Cinnamon crashes only the first time I login, i.e. I boot, log in, Cinnamon crashes, Cinnamon is restarted, I log out and log in again without a crash.

**Steps to reproduce**
Reboot the system and log in.

**Expected behaviour**
No crash.

**Other information**
Logfiles and discussion on Arch Linux forum:
https://bbs.archlinux.org/viewtopic.php?id=236586

**Comment by leigh123linux** [comment]
Either post the logging directly here or your issue doesn't exist, I'm not look through some lame forum for the info.

**Comment by willysr** [comment]
Had the same problem in Slackware-Current VM where i tested Cinnamon 3.8. After restarting cinnamon, it went fine, but next reboot it will happened again.

**Comment by leigh123linux** [comment]
Does disabling system tray applet help?

**Comment by willysr** [comment]
I had it fixed by reverting this patch: https://github.com/linuxmint/Cinnamon/commit/fa9a5c78bfbb6c15b126bf1d79f7d816fecb7b36

**Comment by eli-schwartz** [comment]
For Arch users:

Could you try installing: https://pkgbuild.com/~eschwartz/cinnamon-3.8.0-2-x86_64.pkg.tar.xz (signed by my archlinux-keyring signing key, so you can pacman -U that directly without downloading it first and the signature check will pass).

It reverts that commit.

**Comment by oxydium** [comment]
thank you eli-schwartz

I just installed your patch, I'm testing over several days to tell you.
For the moment no particular worries, no crashes, or other.

Still the problem of excessive use of ram, the process "cinnamon --replace" takes a lot of ram in a short time, and stabilizes at around 900 MB.
same phenomenon with creation of a new user (without installed applets, a raw Cinnamon).
All this on linux-zen and linux-lts kernels, with Nvidia driver (Optimus technology)

to follow therefore...

**Comment by Steffen1989** [comment]
I have just tested newest cinnamon 3.8.0-2 from the Arch community repo:

With activated system tray, Cinnamon still crashes for me.
When system tray is disabled, it does not crash.

**Comment by eli-schwartz** [comment]
Please try cinnamon 3.8.1 which was just released today with 420c0e006839ac850d686cc4d55ad5b6bf1c9259

**Comment by Steffen1989** [comment]
Rebooted four times with cinnamon 3.8.1-1 without a crash. Problem seems to be fixed.
