### ISSUE TITLE
Apps with no icon have invisible icon

### ISSUE THREAD

**Issue by germanfr** [linuxmint/cinnamon#7839]
```
 * Cinnamon version 3.8 and previous versions
 * Distribution - Manjaro
 * 64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog: no significant info
 ```

**Issue**
Some apps have no icon in the menu and window list. They are supposed to fallback to `application-x-executable`, but instead `cinnamon_app_create_icon_texture` returns an invalid icon that paints transparent. Also, if you try to set the gicon of that icon to another icon it stays as is.

**Steps to reproduce**
Sample code to reproduce the bug (this works with apps that have icon):
```js

let app = get_an_app(); // Icon name = "this-icon-does-not-exist"
let icon = app.create_icon_texture(ICON_SIZE); // Should return "application-x-executable" or at least null
if (icon) // It's an invalid icon but a valid object (always true)
    this.actor.add_child(icon); // Adds an invisible icon
else // Never reached
    this.actor.add_child(new St.Icon({ icon_name: 'application-x-executable', ... });
// Icon should be "application-x-executable", but is invisible/transparent
```
Examples of apps without icon are gtk3-icon-browser and some preinstalled usb tools in Mint that I remember.

**Expected behaviour**
I expect them to have the `application-x-executable` icon or return null at least.

**Other information**
![screenshot from 2018-09-06 03-04-35](https://user-images.githubusercontent.com/10391266/45129072-da875580-b181-11e8-95d8-12b32ce452c2.png)

**Clarification**: when I say "an app that has no icon" I mean an app whose icon name has no icon in the current theme.

**Comment by leigh123linux** [comment]
Are you using glib-2.58.0?, if so glib-2.58.1 should fix it

**Comment by germanfr** [comment]
Yes, I'm on glib-2.58.0. If you can confirm it no longer happens with, for example, the Cinnamon menu editor and the Adwaita icon theme then I can close this issue.

**Comment by Vahan86** [comment]
@germanfr, is this still an issue in Cinnamon 4.4?

**Comment by germanfr** [comment]
Yes, icons are still invisible. The bug has not been not fixed yet.

**Comment by Vahan86** [comment]
@germanfr, thanks for the update.
@icarter09, can we mark this issue as a bug?
