### ISSUE TITLE
Windows Key + Up Arrow looses the bottom half of Chrome window

### ISSUE THREAD

**Issue by tkivisik** [linuxmint/Cinnamon#8265]
```
* Cinnamon version - 4.0.8
 * Distribution - Mint 19.1
 * Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 18.0.5 
  direct render: Yes 
 * 64 bit
 ```

**Issue**
WIN Up Arrow behavior on Chrome browser resizing is not consistent. Sometimes halving the window makes whatever was behind Chrome in full screen disappear (or be transparent).

**Steps to reproduce**
Open Firefox, make it full screen (WIN Up Arrow, WIN Up Arrow)
Open Chrome
When Chrome is the active window, keep repeating (WIN Up Arrow)
==> See that sometimes the bottom part of Firefox disappears and you can see the desktop.

**Expected behaviour**
Window resizing is an independent event which does not influence windows behind the current window. Having a Firefox browser in full screen behind Chrome should always stay in front of the desktop, no matter what resizing is done to Chrome in front of it.

**Other information**
I could not replicate it with Firefox in front and Chrome in the back.

**Comment by jaszhix** [comment]
This is fixed by https://github.com/linuxmint/muffin/pull/405.

**Comment by bastiOo** [comment]
happens also with Opera. Indeed Opera very often fills screen about 2/3 in height when clicking "maximize" without any window (from other apps) open. Itried to isolte that problem, but got no chance - happens since update to 19.1/cinnamon 4
And no, it is not fixed

**Comment by jaszhix** [comment]
> And no, it is not fixed

Were you able to test https://github.com/linuxmint/muffin/pull/405? I built binaries from that PR a while ago for another issue.

https://github.com/linuxmint/muffin/files/2771929/muffin-4.0.6-405-8a8227658bda7a582e0e2e33beaaac900653fce6.tar.gz
