### ISSUE TITLE
The mintUpdate launcher is still not showing icon on startup

### ISSUE THREAD

**Issue by hiNom2V2Q95BGAkK4tPt** [linuxmint/cinnamon#8771]
```
 * Cinnamon version (cinnamon --4.2.3+tina)
 * Distribution - (Mint 19.2 | Tina), upgraded through Update Manager from 19.1 to 19.2
 * 64 bit
 * mintUpdate version (5.5.4)
 * syslog: [syslog.txt](https://github.com/linuxmint/cinnamon/files/3472408/syslog.txt)



 ```

**Issue**
The mintUpdate-launcher is included in "Startup Applications" as Update Manager
command: mintupdate-launcher
startup delay: 20 seconds

After 20 seconds the icon blips for a second and then vanishes. A blank space appears in the space of the icon. 
![mintupdate-missing](https://user-images.githubusercontent.com/53823405/62541031-77e28200-b848-11e9-8c98-b069f0c73c85.png)

After quite a period of time a partial/broken icon appears in the invisible space
![mintupdate-broken](https://user-images.githubusercontent.com/53823405/62541093-98124100-b848-11e9-9693-b8e45d4c2b6c.png)

Manually starting the Update Manager changes the icon back to normal, but behaves as a new opened app, and changes the icon position in front
![mintupdate-fixed](https://user-images.githubusercontent.com/53823405/62541386-3900fc00-b849-11e9-8b3e-3fded819a261.png)

**Steps to reproduce**
Not sure if anyone faced this. It happens every time I restart.

**Expected behaviour**
The partial/broken icon should be as shown in the last picture but in the position of 1st/2nd picture

**Other information**
If anything else is needed please comment and I will update my post

**Comment by Scrat-fflm** [comment]
Hello.

I am using Cinnamon 4.2.3 on LM 19.2 x64 with mintupdtate 5.5.4.
I have almost the same problem, but this bug appears randomly: when starting the computer, sometimes the mint update icon is shown, but very often it is not. Restarting Cinnamon always restores the icon.

I have applied the patch suggested by NikoKrause on mintUpdate.py file that is supposed to solve the problem in issue report 8695:
https://github.com/linuxmint/cinnamon/issues/8695

As this bug appears randomly, I guess that it would be difficult to solve, but the suggested patch is not useful for me: the bug is still there ! After having applied the patch, I did a restart and the icon was shown. But starting the computer on the following day, the icon was not shown again ! And now, the problem seems to happen each time I restart.

**Comment by LinuxOnTheDesktop** [comment]
I have the problem of the broken UpdateManager icon - most of the icon is missing and the icon seems unclickable on, thus far, every restart of a laptop that I upgraded (fully) today to 19.2. I can provide the specifications of that laptop. I will try the patch from #8695.

**Comment by Scrat-fflm** [comment]
Hello !
Maybe this could help: restarting the computer from the "Restart" option of the main menu shows the icon. Starting the computer after power off does not show the icon.
I tried this twice this afternoon, and I had the same result: icon is not shown with "cold start" after power off, icon is shown with "warm start" using the "Restart" option of the main menu.
I will perform other restart tests and I will post the results.

**Comment by Scrat-fflm** [comment]
Hello, Scrat again !
Sorry, I was wrong in may last comment. New "warm restart" from the main menu using the "Restart" option... and there is again an empty space instead of the mintupdate icon. So this bug happens randomly and does not depend on how you start or restart the computer.

**Comment by MenthaSuaveolens** [comment]
![UpdateIcon](https://user-images.githubusercontent.com/47174957/63024900-6b91a100-bea8-11e9-8604-312615f1921d.jpg)
I never had this issue with LM19.1. After a fresh install of LM19.2 it almost never shows up after starting the computer. After a while a broken icon is shown. I don't think this bug happens randomly, as I can see it happens also in a VM. mintUpdate 5.5.4

After right-mouse-click and refresh, the icon remains broken

**Comment by Scrat-fflm** [comment]
Hello,
When I say that this bug happens "randomly" on LM 19.2, I mean that sometimes it may happen that the icon is shown after starting the computer, but most of the times it is not shown. With LM 19.1, this was the opposite: the icon was shown most of the times, but sometimes it was not shown.
I think that this is a Cinnamon problem because yesterday, I updated another PC running LM 19.1 XFCE towards LM 19.2 XFCE, and the icon is always shown.

**Comment by megwsgoXfWRJ3DfX** [comment]
> ![UpdateIcon](https://user-images.githubusercontent.com/47174957/63024900-6b91a100-bea8-11e9-8604-312615f1921d.jpg)
> I never had this issue with LM19.1. After a fresh install of LM19.2 it almost never shows up after starting the computer. After a while a broken icon is shown. I don't think this bug happens randomly, as I can see it happens also in a VM. mintUpdate 5.5.4
> 
> After right-mouse-click and refresh, the icon remains broken

This post was from my previous account but I lost access to it. I confirm from this account, yes, this is random. And this also happens in VM. I don't want to mess with mintUpdate.py becasue I tried and is too much noob to do it properly. Can we hope for an early fix? I hope this gets the attenstion of the devs.

**Comment by Scrat-fflm** [comment]
Hello.

This morning, new test on my Lenovo Ideapad 320 with Nvidia graphic card running LM 19.2 Cinnamon x64.

I installed the **mint-meta-xfce** package on the same computer and restarted after power off on an XFCE session: the mintupdate icon is shown. Then power off end restart on a Cinnamon session: the mintupdate icon is not shown.

So it seems that this is really a Cinnamon problem, not a mintupdate problem.

I know that this is holiday time, but I hope to have soon a comment from the devs team.

**Comment by megwsgoXfWRJ3DfX** [comment]
> So it seems that this is really a Cinnamon problem, not a mintupdate problem.
It is, already discussed in [#8695](https://github.com/linuxmint/cinnamon/issues/8695)

But even after updating to the latest version of mintUpdate this happens constantly. In my case it is happening everytime, not random

**Comment by kelebek333** [comment]
You can apply @NikoKrause 's fix. 

Open mintUpdate.py file with following command.

`sudo xed /usr/lib/linuxmint/mintUpdate/mintUpdate.py`

Find following line.


```
            self.statusIcon = Gtk.StatusIcon()
```

add the following 3 lines below the line above. Pay attention to the indents .

```
        self.statusIcon.set_from_icon_name("mintupdate-checking")
        self.statusIcon.set_tooltip_text (_("Checking for updates"))
        self.statusIcon.set_visible(not self.settings.get_boolean("hide-systray"))
```

Finally the lines should look like this.

```
        if os.getenv("XDG_CURRENT_DESKTOP") == "KDE":
            self.statusIcon = StatusIcon(self)
        else:
            self.statusIcon = Gtk.StatusIcon()
        self.statusIcon.set_from_icon_name("mintupdate-checking")
        self.statusIcon.set_tooltip_text (_("Checking for updates"))
        self.statusIcon.set_visible(not self.settings.get_boolean("hide-systray"))

        self.set_status("", _("Checking for updates"), "mintupdate-checking", not self.settings.get_boolean("hide-systray"))
```

**Comment by Scrat-fflm** [comment]
> You can apply @NikoKrause 's fix.

Look at my first post: I have applied this patch and the bug is still there:

> After having applied the patch, I did a restart and the icon was shown. But starting the computer on the following day, the icon was not shown again ! And now, the problem seems to happen each time I restart.

This bugs happens randomly but very often on Cinnamon. It does not happen on XFCE.

**Comment by megwsgoXfWRJ3DfX** [comment]
> You can apply @NikoKrause 's fix.

I already did, and as @Scrat-fflm mentioned, no success.

**Comment by penttila1** [comment]
I have a similar problem. For me it always happens after booting: there is no Update icon, only a space holder for it. The system was upgraded from 19.1 to 19.2. (I had a very similar problem with some releases before which disappeared after a time.)
![missingicon](https://user-images.githubusercontent.com/54205839/63210331-32963e00-c0ed-11e9-8811-c654aed691c2.png)
After right clicking on the tray and turning the tray editor on and than off the icon appears but in a broken way.
![incorrecticon](https://user-images.githubusercontent.com/54205839/63210366-cb2cbe00-c0ed-11e9-965d-d3fde3126577.png)

System info:
System:    Host: PC-afo Kernel: 4.15.0-58-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.2.3 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: Gigabyte model: G31M-ES2L v: x.x serial: <filter> BIOS: Award v: FG 
           date: 02/24/2010 
CPU:       Topology: Dual Core model: Pentium E5500 bits: 64 type: MCP arch: Penryn rev: A 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 vmx bogomips: 11200 
           Speed: 1202 MHz min/max: 1200/2800 MHz Core speeds (MHz): 1: 1473 2: 1466 
Graphics:  Device-1: Intel 82G33/G31 Express Integrated Graphics vendor: Gigabyte driver: i915 
           v: kernel bus ID: 00:02.0 chip ID: 8086:29c2 
           Display: x11 server: X.Org 1.19.6 driver: intel unloaded: fbdev,modesetting,vesa 
           resolution: 1280x1024~60Hz 
           OpenGL: renderer: Mesa DRI Intel G33 v: 1.4 Mesa 19.0.8 direct render: Yes

**Comment by kelebek333** [comment]
Can you try to remove following line from mintUpdate.py.

`        self.set_status("", _("Checking for updates"), "mintupdate-checking", not self.settings.get_boolean("hide-systray"))`

**Comment by megwsgoXfWRJ3DfX** [comment]
I'm waiting for an official patch. The temporary patch is unreliable and not consistent. I hope the devs see this.

**Comment by Scrat-fflm** [comment]
@kelebek333

> Did you remove following line from mintUpdate.py after Niko's fix.

It's not a fix: I just tried to remove this line, then power off and restart, and the mintupdate icon is still not shown ! I have always to restart Cinnamon or to launch mintupdate through the LM menu in order to get it

 I don't think it's a mintupdate bug as there is no problem with XFCE.

**Comment by megwsgoXfWRJ3DfX** [comment]
> I don't think it's a mintupdate bug as there is no problem with XFCE.

I think so too, if this issue is not present in MATE or XFCE then it's definitely Cinnamon's problem.

**Comment by kelebek333** [comment]
Any issue with Niko's way on my systems. However, I deleted the official line added by Clem. I have no issue with both Linux Mint 19.2 and LMDE 3. If you've received updates after your patch, you'll need to reapply the patch.

As a different suggestion, you can try unofflcial version of the gm10's . 

[mintupdate_5.8.0~gm10_all.deb](https://launchpad.net/~gm10/+archive/ubuntu/linuxmint-tools/+files/mintupdate_5.8.0~gm10_all.deb)

**Comment by megwsgoXfWRJ3DfX** [comment]
I am done messing with mintupdate. I have removed the 3 lines I added from @NikoKrause fix and reverted to default. Right now the issue rarely present contrary to as it was before, which was nearly every time. I will wait for an official patch if there is any and hope this will be addressed.

**Comment by Scrat-fflm** [comment]
@kelebek333

How can you say that it's NOT a Cinnamon problem ? Maybe Cinnamon may depend on the mintupdate.py file content, but I and other users have seen that this issue happens only with Cinnamon, and it does NOT happen  with XFCE or MATE. I tried both XFCE and Cinnamon on the same computer with the Niko's fix, and I tied XFCE on another computer with the default mintupdtate: I had no issue withe XFCE on both computers.

On my main computer, I have tried to add the 3 lines of the Niko's fix, then I have tied to remove the following line as you suggested, and I had always this damned issue with Cinnamon.

The problem is that this issue happens RANDOMLY. Sometimes the icon is shown, but very often the icon is not shown, and this happens with the default mintUpdate.py file or the modified one. Modifying this file has no effect on my system. I wonder if it does not depend on the hardware, such as the graphic card, but for me this is a Cinnamon problem and the devs should consider this.

Now I will stop my tests and I have reverted to the default file mintUpdate.py file as a simple workaround for this issue is to restart Cinnamon. I am waiting for a future update of both mintupdate AND Cinnamon.

**Comment by kelebek333** [comment]
Because there is no problem if install the previous version of  update manager (from LM 19.1). It should not be difficult to deduce that the problem is caused by the update manager.

You can try this. Install previous mintupdate from tessa .  [mintupdate_5.4.7_all.deb](packages.linuxmint.com/pool/main/m/mintupdate/mintupdate_5.4.7_all.deb) 

After hold package following command and observe the result.

`apt hold mintupdate`

For unhold.

`apt unhold mintupdate`

**Comment by JosephMcc** [comment]
This is being looked at but it isn't so easy to fix. On two systems here I don't see the problem at all. It makes producing a proper fix very difficult when the problem is hard to reproduce for some.

**Comment by Scrat-fflm** [comment]
Sorry if my comments appear to be not friendly. But I can't understand that kelebek333 does not want to consider that this is a Cinnamon problem, as this issue does not happen with XFCE or MATE and other users agree with this. Maybe this is related to the mintupdate version in Cinnamon, but this remain a Cinnamon problem.

I agree with the fact that this issue is hard to solve as it happens randomly. Maybe  a hardware problem with Cinnamon ? Here is my graphic hardware:

Graphics:  Device-1: Intel HD Graphics 620 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:5916 
           Device-2: NVIDIA GM108M [GeForce 920MX] vendor: Lenovo driver: nvidia v: 390.116 
           bus ID: 01:00.0 chip ID: 10de:134f 
           Display: x11 server: X.Org 1.19.6 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa compositor: muffin tty: N/A 
           OpenGL: renderer: GeForce 920MX/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 direct render: Yes
 
I am always using the NVIDIA graphic card with the 390 driver.

I have tested the proposed fix, on Cinnamon and XFCE, and I can't help anymore as I don't know the Python language. Now, I will not perform any more tests such as downgrading some parts of my system, because excepting this icon issue, Cinnamon works perfectly. I gave you the results of my own tests and now I prefer to wait for official updates.

**Comment by MenthaSuaveolens** [comment]
I did some testing in a VM in order to get the issue clear.

After system-restart, the update-icon is never shown. However if you manually start mintUpdate the icon is displayed right. This is also the case when one changes in PanelSettings the Right panel icon-size!

Now in order to detect the problem faster, I set both update-refresh-times to 1 minute (Preferences). After system-restart, the empty space is shown, but the icon itself is not shown within 5 minutes. As a test I changed the right-panel-icon-size again, and the update-icon popped up, with the indication that an update was available! So it looked that even if there were updates, that the application wasn't capable of setting the icon.

I didn't install the update, but restarted the machine. Again, no indication that an update is available, although the refresh-rate is 1 minute. In the log-file one can see that the updater
has detected the update after powering up the machine.

`08.19@20:39 ++ Launching Update Manager
08.19@20:39 ++ Initial refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
08.19@20:39 ++ Starting refresh (local only)
08.19@20:39 ++ Found 1 software updates
08.19@20:39 ++ Refresh finished
08.19@20:40 ++ Update Manager is in tray mode, performing initial refresh
08.19@20:40 ++ Starting refresh (retrieving lists of updates from remote servers)
08.19@20:40 ++ Found 1 software updates
08.19@20:40 ++ Refresh finished
08.19@20:40 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
08.19@20:41 ++ Update Manager is in tray mode, performing recurring refresh
08.19@20:41 ++ Starting refresh (retrieving lists of updates from remote servers)
08.19@20:41 ++ Found 1 software updates
08.19@20:41 ++ Refresh finished
08.19@20:41 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
08.19@20:42 ++ Update Manager is in tray mode, performing recurring refresh
08.19@20:42 ++ Starting refresh (retrieving lists of updates from remote servers)
08.19@20:42 ++ Found 1 software updates
08.19@20:42 ++ Refresh finished
08.19@20:42 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
08.19@20:43 ++ Update Manager is in tray mode, performing recurring refresh
08.19@20:43 ++ Starting refresh (retrieving lists of updates from remote servers)
08.19@20:43 ++ Found 1 software updates
08.19@20:43 ++ Refresh finished
08.19@20:43 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
08.19@20:44 ++ Update Manager is in tray mode, performing recurring refresh
08.19@20:44 ++ Starting refresh (retrieving lists of updates from remote servers)
08.19@20:44 ++ Found 1 software updates
08.19@20:44 ++ Refresh finished
08.19@20:44 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(`


If you have the patience to wait for an undetermined time, the broken icon pops up. From time to time (in case the icon-height = 32), I get a small white dash in stead of an empty space
![IconHeight32](https://user-images.githubusercontent.com/47174957/63291497-eea96180-c2c3-11e9-9860-053dc704241b.jpg)

**Comment by MenthaSuaveolens** [comment]
To my opinion, there are 2 kind of bugs. One is that the icon is not shown, and the second that the icon is shown only partially. Even when the icon is updated, it is only shown partially. The parts have a with of 14 pixels and a height of 15 pixels.
![UpdateIconBusy](https://user-images.githubusercontent.com/47174957/63414134-7c3b9d00-c3fb-11e9-858d-7e3b90d01d6d.jpg)

**Comment by Scrat-fflm** [comment]
My last tests with the default mintUpdate.py file:

- I updated my NVIDIA driver from 390 to recommended 430.
- restart a default Cinnamon session with the new NVIDIA driver : the icon is not shown.
- power off, then restart a Cinnamon session with software rendering : the icon is not shown.
- restart an XFCE session : the icon is shown.
- restart a default Cinnamon session : the icon is shown !
- on next day, restart a default Cinnamon session: the icon is not shown.

So, this bug happens randomly with Cinnamon only, and this is not a hardware rendering problem.

**Comment by megwsgoXfWRJ3DfX** [comment]
> To my opinion, there are 2 kind of bugs. One is that the icon is not shown, and the second that the icon is shown only partially.

Actually the bug is a single one. First the icon does not show up, leaving a blank space. After quite a lot of time the blank space is replaced by the partial icon. It never stays blank for indefinite time. You just have to give the broken icon enough time to show up.

**Comment by clefebvre** [comment]
Right after observing the issue (either missing or broken icon), can you please do the following:

- Type "alt+F2" then "lg" and press Enter to open Melange (the Cinnamon debugging tool)
- Click on the log tab
- Copy the content of the log and paste it here.
- Kill mintupdate (either with kill, killall or using the right-click->quit option)
- Launch it from terminal with "mintupdate-launcher" and tell us if the icon is still broken or not.
- Paste the logs from Melange again

**Comment by Scrat-fflm** [comment]
Hello Clément.

Of course, when I started the PC to perform your tests, the icon was shown ! This bug happens really randomly !

I started again, and the icon was not shown. Here is the log of the "Melange" tool when the icon is not shown :

info t=2019-08-28T14:46:45Z Cinnamon.AppSystem.get_default() started in 8230 ms
info t=2019-08-28T14:46:45Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-08-28T14:46:46Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-08-28T14:46:46Z PlacesManager: Updating devices
info t=2019-08-28T14:46:46Z loaded at Wed Aug 28 2019 14:46:46 GMT+0200 (CEST)
info t=2019-08-28T14:46:46Z ExtensionSystem started in 2 ms
info t=2019-08-28T14:46:46Z DeskletManager started in 2 ms
info t=2019-08-28T14:46:46Z SearchProviderManager started in 2 ms
info t=2019-08-28T14:46:48Z Loaded applet show-desktop@cinnamon.org in 778 ms
info t=2019-08-28T14:46:48Z Loaded applet removable-drives@cinnamon.org in 20 ms
info t=2019-08-28T14:46:48Z Role locked: tray
info t=2019-08-28T14:46:48Z Loaded applet systray@cinnamon.org in 8 ms
info t=2019-08-28T14:46:48Z Role locked: notifications
info t=2019-08-28T14:46:48Z Loaded applet notifications@cinnamon.org in 166 ms
info t=2019-08-28T14:46:48Z Loaded applet keyboard@cinnamon.org in 18 ms
info t=2019-08-28T14:46:48Z Loaded applet printers@cinnamon.org in 308 ms
info t=2019-08-28T14:46:48Z Loaded applet restart-cinnamon@kolle in 22 ms
info t=2019-08-28T14:46:49Z Loaded applet hwmonitor@sylfurd in 588 ms
info t=2019-08-28T14:46:49Z Loaded applet calendar@cinnamon.org in 98 ms
info t=2019-08-28T14:46:49Z Loaded applet force-quit@cinnamon.org in 6 ms
info t=2019-08-28T14:46:49Z Loaded applet power@cinnamon.org in 368 ms
info t=2019-08-28T14:46:49Z Loaded applet workspace-switcher@cinnamon.org in 278 ms
info t=2019-08-28T14:46:50Z Loaded applet batterymonitor@pdcurtis in 546 ms
info t=2019-08-28T14:46:50Z Role locked: panellauncher
info t=2019-08-28T14:46:50Z Loaded applet grouped-window-list@cinnamon.org in 440 ms
info t=2019-08-28T14:46:51Z Loaded applet sound@cinnamon.org in 86 ms
info t=2019-08-28T14:46:51Z Loaded applet network@cinnamon.org in 620 ms
info t=2019-08-28T14:46:52Z Loaded applet menu@cinnamon.org in 508 ms
info t=2019-08-28T14:46:52Z AppletManager started in 5912 ms
info t=2019-08-28T14:46:52Z Cinnamon took 14534 ms to start
info t=2019-08-28T14:46:53Z Hiding systray: network
info t=2019-08-28T14:46:53Z Adding systray: nvidia-prime (24x24px)
info t=2019-08-28T14:46:53Z Resized nvidia-prime with normalized size (24x24px)
info t=2019-08-28T14:46:53Z Adding systray: blueberry-tray.py (24x24px)
info t=2019-08-28T14:46:53Z Resized blueberry-tray.py with normalized size (24x24px)
info t=2019-08-28T14:46:57Z Adding systray: mintupdate.py (24x24px)
info t=2019-08-28T14:46:57Z Resized mintupdate.py with normalized size (24x24px)

I did not find the "quit" option under right-click, but "Solve the problems -> Restart Cinnamon". For me, restarting Cinnamon always solves the problem. After having restarted Cinnamon, the icon was shown and here is the new log of the "Melange" tool:

info t=2019-08-28T14:50:38Z Cinnamon.AppSystem.get_default() started in 72 ms
info t=2019-08-28T14:50:38Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-08-28T14:50:38Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-08-28T14:50:38Z PlacesManager: Updating devices
info t=2019-08-28T14:50:38Z loaded at Wed Aug 28 2019 14:50:38 GMT+0200 (CEST)
info t=2019-08-28T14:50:38Z ExtensionSystem started in 0 ms
info t=2019-08-28T14:50:38Z DeskletManager started in 0 ms
info t=2019-08-28T14:50:38Z SearchProviderManager started in 0 ms
info t=2019-08-28T14:50:38Z Loaded applet show-desktop@cinnamon.org in 36 ms
info t=2019-08-28T14:50:38Z Loaded applet calendar@cinnamon.org in 36 ms
info t=2019-08-28T14:50:38Z Loaded applet removable-drives@cinnamon.org in 10 ms
info t=2019-08-28T14:50:38Z Loaded applet restart-cinnamon@kolle in 18 ms
info t=2019-08-28T14:50:38Z Loaded applet force-quit@cinnamon.org in 6 ms
info t=2019-08-28T14:50:38Z Loaded applet printers@cinnamon.org in 24 ms
info t=2019-08-28T14:50:38Z Loaded applet hwmonitor@sylfurd in 16 ms
info t=2019-08-28T14:50:38Z Role locked: tray
info t=2019-08-28T14:50:38Z Loaded applet systray@cinnamon.org in 12 ms
info t=2019-08-28T14:50:38Z Loaded applet keyboard@cinnamon.org in 24 ms
info t=2019-08-28T14:50:38Z Loaded applet workspace-switcher@cinnamon.org in 16 ms
info t=2019-08-28T14:50:38Z Role locked: notifications
info t=2019-08-28T14:50:38Z Loaded applet notifications@cinnamon.org in 26 ms
info t=2019-08-28T14:50:38Z Loaded applet power@cinnamon.org in 18 ms
info t=2019-08-28T14:50:38Z Role locked: panellauncher
info t=2019-08-28T14:50:38Z Loaded applet grouped-window-list@cinnamon.org in 28 ms
info t=2019-08-28T14:50:38Z Loaded applet batterymonitor@pdcurtis in 40 ms
info t=2019-08-28T14:50:38Z Loaded applet sound@cinnamon.org in 138 ms
info t=2019-08-28T14:50:38Z Loaded applet network@cinnamon.org in 42 ms
info t=2019-08-28T14:50:39Z Loaded applet menu@cinnamon.org in 252 ms
info t=2019-08-28T14:50:39Z AppletManager started in 832 ms
info t=2019-08-28T14:50:39Z Cinnamon took 1032 ms to start
info t=2019-08-28T14:50:39Z Adding systray: blueberry-tray.py (24x24px)
info t=2019-08-28T14:50:39Z Resized blueberry-tray.py with normalized size (24x24px)
info t=2019-08-28T14:50:39Z Adding systray: nvidia-prime (24x24px)
info t=2019-08-28T14:50:39Z Resized nvidia-prime with normalized size (24x24px)
info t=2019-08-28T14:50:39Z Adding systray: mintupdate.py (24x24px)
info t=2019-08-28T14:50:39Z Resized mintupdate.py with normalized size (24x24px)
info t=2019-08-28T14:50:39Z Hiding systray: network

Good luck for debugging this problem. ;)

**Comment by Scrat-fflm** [comment]
Sorry Clem, I did not understand that you wanted so kill and restart only mintupdate. So here are the logs of Melange with a new test:

1. Starting again the PC from power off: the icon is not shown, and here is the log of Melange:

info t=2019-08-28T14:59:00Z Cinnamon.AppSystem.get_default() started in 7332 ms
info t=2019-08-28T14:59:00Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-08-28T14:59:00Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-08-28T14:59:01Z PlacesManager: Updating devices
info t=2019-08-28T14:59:01Z loaded at Wed Aug 28 2019 14:59:01 GMT+0200 (CEST)
info t=2019-08-28T14:59:01Z ExtensionSystem started in 2 ms
info t=2019-08-28T14:59:01Z DeskletManager started in 2 ms
info t=2019-08-28T14:59:01Z SearchProviderManager started in 2 ms
info t=2019-08-28T14:59:02Z Loaded applet show-desktop@cinnamon.org in 434 ms
info t=2019-08-28T14:59:02Z Role locked: tray
info t=2019-08-28T14:59:02Z Loaded applet systray@cinnamon.org in 12 ms
info t=2019-08-28T14:59:02Z Loaded applet removable-drives@cinnamon.org in 72 ms
info t=2019-08-28T14:59:02Z Loaded applet workspace-switcher@cinnamon.org in 122 ms
info t=2019-08-28T14:59:02Z Loaded applet calendar@cinnamon.org in 88 ms
info t=2019-08-28T14:59:02Z Loaded applet printers@cinnamon.org in 198 ms
info t=2019-08-28T14:59:02Z Loaded applet keyboard@cinnamon.org in 36 ms
info t=2019-08-28T14:59:02Z Role locked: notifications
info t=2019-08-28T14:59:03Z Loaded applet notifications@cinnamon.org in 324 ms
info t=2019-08-28T14:59:03Z Loaded applet restart-cinnamon@kolle in 254 ms
info t=2019-08-28T14:59:03Z Loaded applet force-quit@cinnamon.org in 8 ms
info t=2019-08-28T14:59:03Z Loaded applet hwmonitor@sylfurd in 244 ms
info t=2019-08-28T14:59:03Z Loaded applet power@cinnamon.org in 42 ms
info t=2019-08-28T14:59:03Z Loaded applet sound@cinnamon.org in 260 ms
info t=2019-08-28T14:59:04Z Role locked: panellauncher
info t=2019-08-28T14:59:04Z Loaded applet grouped-window-list@cinnamon.org in 152 ms
info t=2019-08-28T14:59:04Z Loaded applet batterymonitor@pdcurtis in 336 ms
info t=2019-08-28T14:59:04Z Loaded applet network@cinnamon.org in 540 ms
info t=2019-08-28T14:59:05Z Loaded applet menu@cinnamon.org in 470 ms
info t=2019-08-28T14:59:05Z AppletManager started in 4232 ms
info t=2019-08-28T14:59:05Z Cinnamon took 11980 ms to start
info t=2019-08-28T14:59:06Z Hiding systray: network
info t=2019-08-28T14:59:06Z Adding systray: nvidia-prime (24x24px)
info t=2019-08-28T14:59:06Z Resized nvidia-prime with normalized size (24x24px)
info t=2019-08-28T14:59:06Z Adding systray: blueberry-tray.py (24x24px)
info t=2019-08-28T14:59:06Z Resized blueberry-tray.py with normalized size (24x24px)
info t=2019-08-28T14:59:14Z Adding systray: mintupdate.py (24x24px)
info t=2019-08-28T14:59:14Z Resized mintupdate.py with normalized size (24x24px)

After killing and restarting only mintupdate, the icon was shown ant two lines were added to the log:

info t=2019-08-28T15:01:25Z Adding systray: mintupdate.py (24x24px)
info t=2019-08-28T15:01:25Z Resized mintupdate.py with normalized size (24x24px)

**Comment by MenthaSuaveolens** [comment]
@no-icon-shown
```
info t=2019-08-28T16:37:30Z Cinnamon.AppSystem.get_default() started in 4894 ms
info t=2019-08-28T16:37:30Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-08-28T16:37:30Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-08-28T16:37:31Z PlacesManager: Updating devices
info t=2019-08-28T16:37:31Z loaded at Wed Aug 28 2019 16:37:31 GMT+0200 (CEST)
info t=2019-08-28T16:37:31Z ExtensionSystem started in 2 ms
info t=2019-08-28T16:37:31Z DeskletManager started in 2 ms
info t=2019-08-28T16:37:31Z SearchProviderManager started in 2 ms
info t=2019-08-28T16:37:32Z Loaded applet removable-drives@cinnamon.org in 450 ms
info t=2019-08-28T16:37:32Z Loaded applet calendar@cinnamon.org in 206 ms
info t=2019-08-28T16:37:33Z Loaded applet user@cinnamon.org in 234 ms
info t=2019-08-28T16:37:33Z Role locked: notifications
info t=2019-08-28T16:37:33Z Loaded applet notifications@cinnamon.org in 92 ms
info t=2019-08-28T16:37:33Z Loaded applet printers@cinnamon.org in 80 ms
info t=2019-08-28T16:37:33Z Role locked: tray
info t=2019-08-28T16:37:33Z Loaded applet systray@cinnamon.org in 68 ms
info t=2019-08-28T16:37:33Z Loaded applet inhibit@cinnamon.org in 64 ms
info t=2019-08-28T16:37:33Z Loaded applet keyboard@cinnamon.org in 76 ms
info t=2019-08-28T16:37:33Z Loaded applet betterlock in 176 ms
info t=2019-08-28T16:37:33Z Loaded applet redshift@marvel4u in 264 ms
info t=2019-08-28T16:37:34Z Loaded applet workspace-switcher@cinnamon.org in 194 ms
info t=2019-08-28T16:37:34Z Loaded applet power@cinnamon.org in 198 ms
info t=2019-08-28T16:37:34Z Loaded applet cinnamon-timer@jake1164 in 162 ms
info t=2019-08-28T16:37:34Z Role locked: panellauncher
info t=2019-08-28T16:37:34Z Loaded applet grouped-window-list@cinnamon.org in 298 ms
info t=2019-08-28T16:37:35Z Loaded applet sound@cinnamon.org in 602 ms
info t=2019-08-28T16:37:35Z Loaded applet sticky@scollins in 236 ms
info t=2019-08-28T16:37:35Z Loaded applet network@cinnamon.org in 96 ms
info t=2019-08-28T16:37:36Z Loaded applet menu@cinnamon.org in 982 ms
info t=2019-08-28T16:37:36Z AppletManager started in 5178 ms
info t=2019-08-28T16:37:36Z Cinnamon took 11084 ms to start
info t=2019-08-28T16:37:37Z Hiding systray: network
info t=2019-08-28T16:37:37Z Adding systray: blueberry-tray.py (24x24px)
info t=2019-08-28T16:37:37Z Resized blueberry-tray.py with normalized size (24x24px)
info t=2019-08-28T16:37:46Z Adding systray: mintupdate.py (24x24px)
info t=2019-08-28T16:37:46Z Resized mintupdate.py with normalized size (24x24px)
```

kill the process & restart from the terminal => Update-icon is shown ok

**Comment by clefebvre** [comment]
Damn... I can't see anything wrong in these logs..

**Comment by Scrat-fflm** [comment]
Hello Clem.

Maybe you should consider what could be different between XFCE (or Mate) and Cinnamon regarding mintupdate ? If you have other tests to ask...

**Comment by clefebvre** [comment]
oh no, I know why it's happening only in Cinnamon and not in other DEs... it's to do with how we clip the GTK.StatusIcons... whereas in MATE/Xfce it's native/gtk.

What I don't understand is why it's been working well (for mintupdate anyway) until now... and why it no longer does.

And also, why none of us in the dev team manage to reproduce it... that's really annoying.

I'm working on XAppStatusIcon right now, so by the time we get to 19.2 we won't have that problem anymore... but still, in the meantime, I'd like to get this fixed.

**Comment by harlekin777** [comment]
I can confirm this bug for LMDE 3. There are two discussions in the LMDE forums concerning this topic:
https://forums.linuxmint.com/viewtopic.php?f=246&t=299656
https://forums.linuxmint.com/viewtopic.php?f=245&t=292809

**Comment by megwsgoXfWRJ3DfX** [comment]
@clefebvre 
> 
> And also, why none of us in the dev team manage to reproduce it... that's really annoying.
> 
Hi clem, maybe try with a mint live usb. It frequently happens there.

**Comment by megwsgoXfWRJ3DfX** [comment]
@clefebvre 
There seems to be some tricks and trips in [this blog](https://easylinuxtipsproject.blogspot.com/p/first-mint-cinnamon.html#ID3.7) that helps to solve the problem.

**Comment by clefebvre** [comment]
> @clefebvre
> 
> > And also, why none of us in the dev team manage to reproduce it... that's really annoying.
> 
> Hi clem, maybe try with a mint live usb. It frequently happens there.

It can't happen in live sessions. /usr/bin/mintupdate-launcher only launches mintupdate if the session is real (i.e. neither live nor guest). So it's normal for the update manager not to show up in a live session.

**Comment by clefebvre** [comment]
> @clefebvre
> There seems to be some tricks and trips in [this blog](https://easylinuxtipsproject.blogspot.com/p/first-mint-cinnamon.html#ID3.7) that helps to solve the problem.
> 
> > 3.7. Some people have difficulty noticing the blue icon in the system tray, that signifies that new updates are available.... In that case you can make available updates more prominent like this:
> > Menu - Preferences - Startup Applications
> > Click the + button (Add) - Custom command
> > Name: Update Window
> > Command: mintupdate
> > Startup delay: set it at 99. Because otherwise it may conflict with the existing startup application mintupdate-launcher, which launches after 20 seconds.
> > Click Save.
> > Now you should be presented with the window of Update Manager, 99 seconds after you log in. You can't overlook it: it's "in your face".
> > The disadvantage is, that you also get to see it when there are no updates at all. But that's better than overlooking updates that need to be installed....

That's not a solution, and it doesn't help troubleshooting the issue. it's just a workaround, and a bad one too.. instead of calling mintupdate @99s, simply call mintupdate-launcher instead. That'll just fix the systray if it's broken but it won't pop the window into your face.

**Comment by megwsgoXfWRJ3DfX** [comment]
> Damn... I can't see anything wrong in these logs..

Well, it's still random in my system. I have no idea what is causing this either.

**Comment by penttila1** [comment]
Hi Clem,

Here is the requested info:
After log-in there is no icon at all, only a space holder (see my earlier comment):

info t=2019-09-01T13:14:41Z Cinnamon.AppSystem.get_default() started in 6564 ms
info t=2019-09-01T13:14:41Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-09-01T13:14:41Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-09-01T13:14:42Z PlacesManager: Updating devices
info t=2019-09-01T13:14:42Z loaded at Sun Sep 01 2019 13:14:42 GMT+0200 (CEST)
info t=2019-09-01T13:14:42Z ExtensionSystem started in 0 ms
info t=2019-09-01T13:14:42Z DeskletManager started in 2 ms
info t=2019-09-01T13:14:42Z SearchProviderManager started in 2 ms
info t=2019-09-01T13:14:42Z Loaded applet show-desktop@cinnamon.org in 114 ms
info t=2019-09-01T13:14:42Z Loaded applet user@cinnamon.org in 122 ms
info t=2019-09-01T13:14:42Z Loaded applet trash@cinnamon.org in 96 ms
info t=2019-09-01T13:14:42Z Role locked: tray
info t=2019-09-01T13:14:42Z Loaded applet systray@cinnamon.org in 18 ms
info t=2019-09-01T13:14:43Z Loaded applet calendar@cinnamon.org in 158 ms
info t=2019-09-01T13:14:43Z Role locked: panellauncher
info t=2019-09-01T13:14:43Z Loaded applet panel-launchers@cinnamon.org in 388 ms
info t=2019-09-01T13:14:43Z Loaded applet keyboard@cinnamon.org in 36 ms
info t=2019-09-01T13:14:43Z Loaded applet removable-drives@cinnamon.org in 16 ms
info t=2019-09-01T13:14:43Z Role locked: notifications
info t=2019-09-01T13:14:43Z Loaded applet notifications@cinnamon.org in 82 ms
info t=2019-09-01T13:14:43Z Loaded applet window-list@cinnamon.org in 86 ms
info t=2019-09-01T13:14:43Z Loaded applet power@cinnamon.org in 62 ms
info t=2019-09-01T13:14:43Z Loaded applet sound@cinnamon.org in 144 ms
info t=2019-09-01T13:14:44Z Loaded applet network@cinnamon.org in 124 ms
info t=2019-09-01T13:14:44Z Loaded applet menu@cinnamon.org in 446 ms
info t=2019-09-01T13:14:44Z AppletManager started in 2166 ms
info t=2019-09-01T13:14:44Z Cinnamon took 9230 ms to start
info t=2019-09-01T13:14:44Z Hiding systray: network
info t=2019-09-01T13:14:56Z Adding systray: mintupdate.py (24x24px)
info t=2019-09-01T13:14:56Z Resized mintupdate.py with normalized size (24x24px)

After killing and starting it with mintupdate-launcher the icon fully and correctly appears for me and after some seconds even it green colour is representing the state correctly. Here is the log after restarting:

info t=2019-09-01T13:14:41Z Cinnamon.AppSystem.get_default() started in 6564 ms
info t=2019-09-01T13:14:41Z loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
info t=2019-09-01T13:14:41Z added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
info t=2019-09-01T13:14:42Z PlacesManager: Updating devices
info t=2019-09-01T13:14:42Z loaded at Sun Sep 01 2019 13:14:42 GMT+0200 (CEST)
info t=2019-09-01T13:14:42Z ExtensionSystem started in 0 ms
info t=2019-09-01T13:14:42Z DeskletManager started in 2 ms
info t=2019-09-01T13:14:42Z SearchProviderManager started in 2 ms
info t=2019-09-01T13:14:42Z Loaded applet show-desktop@cinnamon.org in 114 ms
info t=2019-09-01T13:14:42Z Loaded applet user@cinnamon.org in 122 ms
info t=2019-09-01T13:14:42Z Loaded applet trash@cinnamon.org in 96 ms
info t=2019-09-01T13:14:42Z Role locked: tray
info t=2019-09-01T13:14:42Z Loaded applet systray@cinnamon.org in 18 ms
info t=2019-09-01T13:14:43Z Loaded applet calendar@cinnamon.org in 158 ms
info t=2019-09-01T13:14:43Z Role locked: panellauncher
info t=2019-09-01T13:14:43Z Loaded applet panel-launchers@cinnamon.org in 388 ms
info t=2019-09-01T13:14:43Z Loaded applet keyboard@cinnamon.org in 36 ms
info t=2019-09-01T13:14:43Z Loaded applet removable-drives@cinnamon.org in 16 ms
info t=2019-09-01T13:14:43Z Role locked: notifications
info t=2019-09-01T13:14:43Z Loaded applet notifications@cinnamon.org in 82 ms
info t=2019-09-01T13:14:43Z Loaded applet window-list@cinnamon.org in 86 ms
info t=2019-09-01T13:14:43Z Loaded applet power@cinnamon.org in 62 ms
info t=2019-09-01T13:14:43Z Loaded applet sound@cinnamon.org in 144 ms
info t=2019-09-01T13:14:44Z Loaded applet network@cinnamon.org in 124 ms
info t=2019-09-01T13:14:44Z Loaded applet menu@cinnamon.org in 446 ms
info t=2019-09-01T13:14:44Z AppletManager started in 2166 ms
info t=2019-09-01T13:14:44Z Cinnamon took 9230 ms to start
info t=2019-09-01T13:14:44Z Hiding systray: network
info t=2019-09-01T13:14:56Z Adding systray: mintupdate.py (24x24px)
info t=2019-09-01T13:14:56Z Resized mintupdate.py with normalized size (24x24px)
info t=2019-09-01T13:23:29Z Adding systray: mintupdate.py (24x24px)
info t=2019-09-01T13:23:29Z Resized mintupdate.py with normalized size (24x24px)

I hope this helps a little.

**Comment by clefebvre** [comment]
Hi,

Can you take the following versions of mintupdate for a ride and see if you can reproduce the issue with them as well?

http://packages.linuxmint.com/pool/main/m/mintupdate/mintupdate_5.4.7_all.deb
https://launchpad.net/~gm10/+archive/ubuntu/linuxmint-tools/+files/mintupdate_5.8.0~gm10_all.deb

**Comment by Scrat-fflm** [comment]
Hello Clem.

As I am new to Linux and ?not easy with modifications of the system, can you tell me how to install these files ?  When I double-click on the first one, it tells me that it is an error because a more recent version exists.

**Comment by Scrat-fflm** [comment]
Hello Clem.

I performed several power off -> start or restart without power off with the 5.4.7 version, and the icon was always shown.

Then I restored the system at version 5.5.4 using a Timeshift snapshot, the icon was shown at first restart, but not shown after power off -> start.

So the 5.4.7 version seems OK.

But I can't install the 5.8.0:
> Error: the dependency cannot be satisfied : mint-common (>= 1:2.0.2~gm10)

**Comment by MenthaSuaveolens** [comment]
I can't install none of the .deb-files (I tried this on 2 machines)
mintupdate_5.8.0~gm10_all.deb returns "Error: Dependency is not satisfiable: mint-common (>= 1:2.0.5~gm10)"
mintupdate_5.4.7_all.deb returns "Error: A later version is already installed"

**Comment by Scrat-fflm** [comment]
@MenthaSuaveolens:
Before installing 5.4.7 version, you have to uninstall current mintupdate (should be 5.5.4) using Synaptic manager.
Perform à Timeshift snapshot before modifying your system.

**Comment by MenthaSuaveolens** [comment]
After removing version 5.5.4 and installing 5.4.7 and restarting the machine, the update-icon is shown all right (update available : mintupdate 5.5.4)

**Comment by clefebvre** [comment]
oh no, you can install a deb with a lower version from the terminal... "sudo dpkg -i myfile.deb". anyway, thanks guys, this helps a lot. I'll start preparing debs between 5.4.7 and the 5.5.4 to understand where the issue started.

**Comment by clefebvre** [comment]
The ZIP below contains .deb files versioned 5.4.7.4, 5.4.7.5 and 5.4.7.6:

[5.4.7-builds.zip](https://github.com/linuxmint/cinnamon/files/3569441/5.4.7-builds.zip)

Please test these builds one by one to find out if they have the problem we're trying to fix.

**Comment by MenthaSuaveolens** [comment]
My test-sequence 

**Case1**
sudo dpkg -i mintupdate_5.4.7.4_all.deb
shutdown -r 0
==> Update-icon is shown, 1 update available (mintupdate). Installing latest version
==> More updates available (I don't install them)
restart computer
=> no icon shown

**Case2**
sudo dpkg -i mintupdate_5.4.7.5_all.deb
shutdown -r 0
==> Update-icon is shown, 1 update available (mintupdate). Installing latest version
==> More updates available (I don't install them)
restart computer
=> broken icon shown (only a small white bottom-line
![BrokenIcon](https://user-images.githubusercontent.com/47174957/64178278-77e29b80-ce61-11e9-860b-deee8379ab50.jpg)

**Case3**
sudo dpkg -i mintupdate_5.4.7.6_all.deb
shutdown -r 0
=> Update-icon is shown. Pressing the icon now gives a warning that the updater must be updated

I don't update and restart the computer
=> Update-icon is shown. I update. More updates available ( (I don't install them)
restart computer
=> no icon shown (Well it's a dark placeholder that is shown)

My Conclusion, all 3 older versions of the updater seem ok

**Comment by claudiux** [comment]
Tests on Cinnamon 4.2.3 nightly-build:

```
sudo dpkg -i mintupdate_5.4.7.4_all.deb
mintupdate
```
The icon appears. Then log-off/log-on. The icon also appears. :+1: 

```
sudo dpkg -i mintupdate_5.4.7.5_all.deb
mintupdate
```
The icon appears. Then log-off/log-on. The icon also appears. :+1: 

 ```
sudo dpkg -i mintupdate_5.4.7.6_all.deb
mintupdate
```
The icon appears. Then log-off/log-on. The icon also appears. :+1: 

 Same tests with reboot instead of log-off/log-on. Same conclusions.

These 3 versions seem to be OK.

**Comment by clefebvre** [comment]
cool, I'll prepare new ones.

**Comment by clefebvre** [comment]
Here are two builds on top of 5.5.4.

[5.5.4-builds.zip](https://github.com/linuxmint/cinnamon/files/3570495/5.5.4-builds.zip)

**Comment by Scrat-fflm** [comment]
Hello.

Testing 5.5.4.2: icon is shown at first restart, not shown at two following restarts (with or without power off).

So I am going to test the other 5.4.7....

**Comment by Scrat-fflm** [comment]
Note for test with 5.5.4.2: when the icon is shown after restarting Cinnamon, it is inactive. Clicking on it does not open the update manager.

Downgrading to  5.4.7.6 :
- first restart without power off : the icon not shown !
- restarting three times more, with or without power off: the icon is shown.

I am not sure for icon not shown at first restart after installing 5.4.7.6 : maybe I did not wait enough time before setting power off for a new restart.

For those who have tested 5.4.7.6: did you perform several restarts ? As this bug happens randomly, you should test several times.

**Comment by MenthaSuaveolens** [comment]
Test-sequence

**1. Upgrade to 5.5.4.2**

Restart computer => Icon is ok (but not active as Scrat-fflm mentioned)
Restart computer => Icon is ok but not active
Restart computer => Icon is ok but not active
Restart computer => Icon is ok but not active

**2. Upgrade to 5.5.4.11**
Restart computer => Icon is ok but not active
Restart computer => Icon is ok but not active

**3. Downgrade to 5.4.7.6**
Restart computer => Icon is ok (active : updatemanager needs to be updated)
Restart computer => Icon is ok
Restart computer => Icon is ok
Restart computer => Icon is ok

**4. Updating by update-manager**
Restart computer => **Icon is NOT ok**
Restart computer => **Icon is NOT ok**

**Comment by clefebvre** [comment]
@MenthaSuaveolens what do you mean by "not active" exactly?

**Comment by clefebvre** [comment]
oh sorry, I see, insensitive... I can reproduce it.

**Comment by clefebvre** [comment]
Sorry about this, this was my mistake (and a silly one) :)

Here are the same builds with the insensitivity fixed.

[5.5.4-3and4.zip](https://github.com/linuxmint/cinnamon/files/3571915/5.5.4-3and4.zip)

**Comment by Scrat-fflm** [comment]
@clfebvre:
For me, with 5.5.4.2, the icon was shown only at first restart, not at the following ones. When I restart Cinnamon to restore the icon, the icon is insensitive: clicking on it does not open the update manager.

**Comment by Scrat-fflm** [comment]
Installing 5.5.4.3 and performing five tests:

1. power off -> Start : the icon is shown and sensitive.
2. power off -> Start : the icon is shown and sensitive.
3. restart computer without power off: the icon is shown and sensitive.
4. log out -> log in without restarting the computer: the icon appears quickly, disappears, comes back after 3 or 5 seconds and is sensitive.
5. log out -> log in without restarting the computer: the icon appears quickly, disappears, comes back after 3 or 5 seconds and is sensitive.

So the 5.5.4.3 version seems OK. I will stay with this version to perform other tests with it tomorrow (or today as we are already tomorrow at 1.04 AM ! ). I want to check a "cold start" in the morning.

**Comment by claudiux** [comment]
5.5.4.4 version tested on Cinnamon 4.2.3 nightly build, into a virtual box.

  1.
```
sudo dpkg -i mintupdate_5.5.4.4_all.deb
mintupdate
```
The icon is shown and sensitive.

  2. power off -> Start : the icon is shown and sensitive.
  3. idem 2.
  4. restart computer without power off: the icon is shown and sensitive.
  5. log out -> log in without restarting the computer: the icon is shown and sensitive, without disappearing.
  6. idem 5.

The 5.5.4 version seems OK.

**Comment by megwsgoXfWRJ3DfX** [comment]
@clefebvre Hi Clem, I have not tested with the packages you provided but there is another thing. Last few days I've got some updates and after installing them I'm not getting the bug! Not a single time. I'm using the latest 5.5.4 version. I think some of those updates fixed it. I'm not sure which one but I'll post them here.
![up1](https://user-images.githubusercontent.com/54113280/64222285-1c46fb00-cebf-11e9-89f8-ac0523f259f1.png)
![up2](https://user-images.githubusercontent.com/54113280/64222290-21a44580-cebf-11e9-9120-beabf05647c6.png)
![up3](https://user-images.githubusercontent.com/54113280/64222318-2ec13480-cebf-11e9-8370-565d87f88355.png)
![up4](https://user-images.githubusercontent.com/54113280/64222323-31bc2500-cebf-11e9-9b22-2874e4f22b91.png)

**Comment by Scrat-fflm** [comment]
@clefebvre:

Hello Clem.

After my tests with 5.5.4.3 last night, "cold start" this morning with 5.5.4.3: the icon is shown and sensitive.

Then, installing 5.5.4.4 and performing the same five tests:

    power off -> Start : the icon is shown and sensitive.
    power off -> Start : the icon is shown and sensitive.
    restart computer without power off: the icon is shown and sensitive.
    log out -> log in without restarting the computer: the icon appears quickly, disappears, comes back after 3 or 5 seconds and is sensitive.
    log out -> log in without restarting the computer: the icon appears only after 3 or 5 seconds and is sensitive.

So version 5.5.4.4 seems OK. The icon is shown almost immediately after power of -> Start or after restart without power off. There is just a strange behaviour after log out -> log in : the icon is shown and sensitive, but either the icon appears briefly, disappears and comes back after a few seconds, or it may appear only after a few seconds.

@megwsgoXfWRJ3DfX: each day I install all available updates. So my system had the latest updates yesterday and this did not solve the bug with 5.5.4 for me.

**Comment by clefebvre** [comment]
Ok, it looks good. Just one more build to make sure I've got this right.. 

[5.5.4.0.zip](https://github.com/linuxmint/cinnamon/files/3574230/5.5.4.0.zip)

**Comment by Scrat-fflm** [comment]
Sorry Clem, but after my five successful tests of 5.5.4.4 this morning, I set power off, then I restarted this afternoon... and the icon is not shown ! This bug is absolutely random !

I am going to test the new debs...

**Comment by Scrat-fflm** [comment]
Installing the new deb 5.5.4.0 and performing the same five tests as with 5.5.4.4:

1. power off -> Start : the icon is shown and sensitive.
2. power off -> Start : the icon is shown and sensitive.
3. restart computer without power off: the icon is shown and sensitive.
4. log out -> log in without restarting the computer: the icon appears quickly, disappears, comes back after 3 or 5 seconds and is sensitive.
5. log out -> log in without restarting the computer: the icon appears only after 3 or 5 seconds and is sensitive.

So, for these five tests,  the 5.5.4.0 behaviour is the same as the 5.5.4.4 one.

Adding a new test with 5.5.4.0:
6. power off -> Start : the icon is shown and sensitive.

The new 5.5.4.0 seems to solve the problem as it passed successfully six tests, but I am not sure as the bug happens randomly. More tests are needed as 5.5.4.4 passed successfully five tests and failed at the sixth one.

But something remains strange: the delay for showing the icon seems to be longer when doing simple log out -> log in than when restarting the computer.

Conclusion of my tests :
- old 5.5.4 : the icon is not shown very often, and sometimes it is shown.
- new 5.5.4.4 : the icon is shown very often, but sometimes it is not shown, so this is an improvement.
- new 5.5.4.0: until now, the icon was shown on each of my six tests, but not sure that the problem is definitely solved.

**Comment by Scrat-fflm** [comment]
Info: I just received an update for Cinnamon. After updating Cinnamon from 4.2.3 to 4.2.4, log out -> log in without restarting the computer, and the icon is shown as quickly as when restarting the computer.
Is (new mintupdate 5.5.4.0 + new Cinnamon 4.2.4) the solution ? Wait for more tests and see...

**Comment by clefebvre** [comment]
no, the Cinnamon update fixes other things, but it's not related to this at all.

**Comment by megwsgoXfWRJ3DfX** [comment]
yeah, It says in the changelog what it fixes. So far I'm not encountering the bug anymore after those previous updates. I don't want to jinx it anymore :smile: 
@clefebvre Have you been able to reproduce the bug in your test, with or without VM?

**Comment by Scrat-fflm** [comment]
New restart with 5.5.4.0 after power off this afternoon (7th test of this day)... 
... and the icon is still shown ! :grin:

**Comment by clefebvre** [comment]
>  @clefebvre Have you been able to reproduce the bug in your test, with or without VM?

No, never :(

**Comment by clefebvre** [comment]
Well... I could reproduce the bug in the BETA. The one we fixed in 5.5.1 (https://github.com/linuxmint/mintupdate/commit/e6a6f21cc60f63da1f2a74f14754f1508e306bc4). But this one, no, never.

**Comment by Scrat-fflm** [comment]
Maybe this could help ?

I received my new Lenovo laptop shipped with LM 19 one year ago and all was OK.

Then I updated to LM 19.1. The bug appeared with LM 19.1, but not often. Sorry, I did not check what was the mintupdate version when it happened for the first time.

Finally, I updated to LM 19.2, and after that I received several updates of mintupdate in a few days, the last one being 5.5.4. With LM 19.2, the bug happened very often, almost every time. Now, with the new mintupdate 5.5.4.0, it seems to have disappeared.

**Comment by clefebvre** [comment]
Anybody else on 5.5.4.0 before I send an official update? @MenthaSuaveolens @claudiux @megwsgoXfWRJ3DfX ?

**Comment by Scrat-fflm** [comment]
@clefebvre :

Hello Clem.

All is OK when starting the computer this morning: the icon is still shown and sensitive.
Until now, I have done 8 starts or restarts without problem with the 5.5.4.0 version.
It is difficult to say that the problem is fully solved as the bug happens randomly, but 5.5.4.0 is a great improvement.

**Comment by clefebvre** [comment]
Yes, but: 

- I can't reproduce it here
- It's random anyway
- I fixed quite a few things which didn't look right and looked suspicious in the code, but none of them 100% explained what was going on

So I still need feedback from a few more people before I can push this fix and close this issue.

**Comment by megwsgoXfWRJ3DfX** [comment]
Yeah, I'm on official 5.5.4

**Comment by clefebvre** [comment]
5.5.4.0 isn't 5.5.4... that issue is present in 5.5.4, but potentially fixed on 5.5.4.0.

**Comment by clefebvre** [comment]
sorry, I understand it's a bit confusing. I'm keeping "5.5.4.1" for when the fix is officially published basically :)

**Comment by harlekin777** [comment]
@clem, can i install the 5.5.4.0. on LMDE without breaking the system?

**Comment by clefebvre** [comment]
@harlekin777 yes

**Comment by harlekin777** [comment]
@clefebvre

First I would like to mention that on my LMDE 3 system the bug with the old mintupdate 5.5.4 appeared with 100% reliability (icon never showed up).
Installing the new deb mintupdate 5.5.4.0 and performing the five tests mentioned above:

1.    power off -> Start
2.    power off -> Start
3.    restart computer without power off
4.    log out -> log in without restarting the computer
5.    log out -> log in without restarting the computer

After every test the icon is shown and sensitive. I observed that the icon appears every time after a delay of ca. 6 or 7 seconds, which seems to be a little longer than before the bug appeared. I would say, the delay is tolerable.

Same result after applying updates (firefox 68.1.0 and cinnamon 4.2.4) and running all five tests again.

Conclusion: on my LMDE 3 system the new deb mintupdate 5.5.4.0 so far works well. The delay of the icon showing up may be considered a minor issue.

Thank you very much. A big improvement.

**Comment by megwsgoXfWRJ3DfX** [comment]
@harlekin777 I think you can change the delay in "Startup Applications".

**Comment by harlekin777** [comment]
@megwsgoXfWRJ3DfX
Thank you very much!

**Comment by harlekin777** [comment]
The bigger delay is apparently the result of Cinnamon loading faster than before. So it is a good thing.

**Comment by clefebvre** [comment]
Thanks everyone for the useful feedback. I couldn't have fixed that without you.

This is pushed towards the Mint 19.2 and LMDE 3 repositories as mintupdate 5.5.4.1.
