### ISSUE TITLE
Visual bug on "Shift" key in OSK

### ISSUE THREAD

**Issue by DuMuT6p** [linuxmint/cinnamon#8938]
```
 * Cinnamon version - 4.0.10
 * Distribution - Mint 19.1
 * Graphics hardware *and* driver used - Nvidia proprietary driver
 * 64 bit
 ```

**Issue**
When "Shift" hardware key is used in combination with mouse click, the keyboard continues to display shift-modified keys, but their click produce normal output. To note that using the OSK "Shift" doesn't reproduce the issue.

**Steps to reproduce**
1. Open OSK
2. Hold hardware "Shift" and click an OSK letter with the mouse.
3. Release "Shift" and click a letter

**Expected behaviour**
Releasing "Shift" should adjust the display of the keys.

**Comment by icarter09** [comment]
Linux Mint 19.2
Cinnamon 4.2.4

I was unable to reproduce this problem. When I released "Shift", the OSK reflected the key being unpressed and the display of the keys all went back to lowercase on the OSK.

**Comment by icarter09** [comment]
@DuMuT6p are you still experiencing this issue?

**Comment by JosephMcc** [comment]
I can't reproduce this either. However, pushing the hardware shift doesn't change the display of the keyboard either. The output is correct though.

**Comment by DuMuT6p** [comment]
I upgraded to 19.2 and updated with all available updates as of today. Issue still persist. 
@JosephMcc here it still chagnes, but gets stuck.

**Comment by icarter09** [comment]
I'm not able to reproduce this on Cinnamon 4.4.4

**Comment by icarter09** [comment]
Cinnamon 4.8.6
Mint 20.1 64bit

Still not able to reproduce this issue.

**Comment by DuMuT6p** [comment]
It's still reproducible for me on 
Cinnamon 4.8.6
Mint 20.1 64bit

However I haven't done a clean install. Only upgraded since Mint 19.1. 
I noticed also that the visual upper case doesn't change right away on holding shift for a breaf time, but if I had clicked a hardware key it is upper case.
