### ISSUE TITLE
Grouped windows list: windows disappear...

### ISSUE THREAD

**Issue by kolayne** [linuxmint/cinnamon#9153]
```
 * Cinnamon 4.4.8 not using daily ppa
 * Mint 19.3
 * NVidia Geforce 940MX (nvidia-driver-435)
 * 64 bit
 ```

**Issue**
If you switch to a workspace, holding a window on top, and move back, still holding this window, it disappears from the GWL on all the desktops.
Sometimes the window disappears after the first desktop switch.

**Steps to reproduce**
0. Create at least two desktops, switch to a left one
1\. Open any window (for example, Nemo)
2. Place the cursor on the window's title
3. Holding the mouse button, press right arrow key
4. Holding the mouse button, press left arrow key

**Expected behaviour**
After both of the desktop switches, the window appears as opened in the active desktop's GWL

**Other information**
I guess, this may be related to #9080 

<details>
<summary>GWL configuration info</summary>

```JSON
{
    "layout": {
        "type": "layout",
        "pages": [
            "generalPage",
            "panelPage",
            "thumbnailsPage",
            "contextMenuPage"
        ],
        "generalPage": {
            "type": "page",
            "title": "General",
            "sections": [
                "generalSection",
                "hotKeysSection"
            ]
        },
        "panelPage": {
            "type": "page",
            "title": "Panel",
            "sections": [
                "appButtonsSection"
            ]
        },
        "thumbnailsPage": {
            "type": "page",
            "title": "Thumbnails",
            "sections": [
                "thumbnailsSection",
                "hoverPeekSection"
            ]
        },
        "contextMenuPage": {
            "type": "page",
            "title": "Context Menu",
            "sections": [
                "contextMenuSection"
            ]
        },
        "generalSection": {
            "type": "section",
            "title": "Behavior",
            "keys": [
                "group-apps",
                "scroll-behavior",
                "left-click-action",
                "middle-click-action",
                "show-all-workspaces"
            ]
        },
        "appButtonsSection": {
            "type": "section",
            "title": "Application Buttons",
            "keys": [
                "title-display",
                "launcher-animation-effect",
                "number-display",
                "pinned-apps",
                "enable-app-button-dragging"
            ]
        },
        "hotKeysSection": {
            "type": "section",
            "title": "Hot Keys",
            "keys": [
                "cycleMenusHotkey",
                "show-apps-order-hotkey",
                "show-apps-order-timeout"
            ]
        },
        "thumbnailsSection": {
            "type": "section",
            "title": "Thumbnails",
            "keys": [
                "thumbnail-scroll-behavior",
                "show-thumbnails",
                "animate-thumbnails",
                "vertical-thumbnails",
                "sort-thumbnails",
                "highlight-last-focused-thumbnail",
                "onclick-thumbnails",
                "thumbnail-timeout",
                "thumbnail-size"
            ]
        },
        "hoverPeekSection": {
            "type": "section",
            "title": "Hover Peek",
            "keys": [
                "enable-hover-peek",
                "hover-peek-time-in",
                "hover-peek-time-out",
                "hover-peek-opacity"
            ]
        },
        "contextMenuSection": {
            "type": "section",
            "title": "",
            "keys": [
                "show-recent",
                "autostart-menu-item",
                "launch-new-instance-menu-item",
                "monitor-move-all-windows"
            ]
        }
    },
    "number-display": {
        "type": "checkbox",
        "default": true,
        "description": "Show window count numbers",
        "value": true
    },
    "title-display": {
        "type": "combobox",
        "default": 1,
        "description": "Button label",
        "options": {
            "None": 1,
            "Application name": 2,
            "Window title": 3,
            "Window title (only for the focused window)": 4
        },
        "value": 1
    },
    "scroll-behavior": {
        "type": "combobox",
        "default": 1,
        "description": "Mouse wheel scroll action",
        "options": {
            "None": 1,
            "Cycle apps": 2,
            "Cycle windows": 3
        },
        "value": 1
    },
    "left-click-action": {
        "type": "combobox",
        "default": 2,
        "description": "Left click action",
        "options": {
            "None": 1,
            "Toggle activation of last focused window": 2,
            "Cycle windows": 3
        },
        "value": 2
    },
    "middle-click-action": {
        "type": "combobox",
        "default": 3,
        "description": "Middle click action",
        "options": {
            "None": 1,
            "Launch new app instance": 2,
            "Close last focused window in group": 3
        },
        "value": 3
    },
    "pinned-apps": {
        "type": "generic",
        "default": [
            "firefox.desktop",
            "org.gnome.Terminal.desktop",
            "nemo.desktop"
        ],
        "value": [
            "google-chrome.desktop",
            "jetbrains-clion.desktop",
            "org.gnome.Terminal.desktop",
            "nemo.desktop"
        ]
    },
    "group-apps": {
        "type": "checkbox",
        "default": true,
        "description": "Group windows by application",
        "value": true
    },
    "show-all-workspaces": {
        "type": "checkbox",
        "default": false,
        "description": "Show windows from all workspaces",
        "value": false
    },
    "enable-app-button-dragging": {
        "type": "checkbox",
        "default": true,
        "description": "Enable app button dragging",
        "value": true
    },
    "launcher-animation-effect": {
        "type": "combobox",
        "default": 3,
        "description": "Launcher animation",
        "options": {
            "None": 1,
            "Fade": 2,
            "Scale": 3
        },
        "value": 3
    },
    "cycleMenusHotkey": {
        "type": "keybinding",
        "default": "<Super>space",
        "description": "Global hotkey for cycling through thumbnail menus",
        "value": "<Super>space"
    },
    "show-apps-order-hotkey": {
        "type": "keybinding",
        "default": "<Super>grave",
        "description": "Global hotkey to show the order of apps",
        "value": "<Super>grave"
    },
    "show-apps-order-timeout": {
        "type": "spinbutton",
        "default": 2500,
        "min": 100,
        "max": 10000,
        "step": 10,
        "units": "milliseconds",
        "description": "Duration of the apps order display on hotkey press",
        "value": 2500
    },
    "thumbnail-timeout": {
        "dependency": "!onclick-thumbnails",
        "type": "combobox",
        "default": 250,
        "description": "Delay before showing thumbnails",
        "options": {
            "50 ms": 50,
            "250 ms": 250,
            "500 ms": 500
        },
        "value": 250
    },
    "thumbnail-size": {
        "type": "combobox",
        "default": 6,
        "description": "Thumbnail size",
        "options": {
            "Small": 3,
            "Medium": 6,
            "Large": 9,
            "Largest": 12
        },
        "value": 6
    },
    "thumbnail-scroll-behavior": {
        "type": "checkbox",
        "default": false,
        "description": "Cycle windows on mouse wheel scroll",
        "value": false
    },
    "show-thumbnails": {
        "type": "checkbox",
        "default": true,
        "description": "Show thumbnails",
        "value": true
    },
    "animate-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Animate thumbnails",
        "value": false
    },
    "vertical-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Enable vertical thumbnails",
        "value": false
    },
    "sort-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Sort thumbnails according to the last focused windows",
        "value": false
    },
    "highlight-last-focused-thumbnail": {
        "type": "checkbox",
        "default": true,
        "description": "Highlight the thumbnail of the last focused window",
        "value": true
    },
    "onclick-thumbnails": {
        "type": "checkbox",
        "default": false,
        "description": "Click to show thumbnails",
        "value": false
    },
    "show-recent": {
        "type": "checkbox",
        "default": true,
        "description": "Show recent items",
        "value": true
    },
    "autostart-menu-item": {
        "type": "checkbox",
        "default": false,
        "description": "Show autostart option",
        "value": false
    },
    "launch-new-instance-menu-item": {
        "type": "checkbox",
        "default": true,
        "description": "Show new window option",
        "tooltip": "Shows the \"New Window\" option in an app's context menu if it doesn't already have one from the app's own action menu items.",
        "value": true
    },
    "monitor-move-all-windows": {
        "type": "checkbox",
        "default": true,
        "description": "Apply the monitor move option to all windows",
        "tooltip": "When clicking \"Move to monitor\" in the context menu, this option will move all of an app's windows instead of just the last focused window from the app.",
        "value": true
    },
    "enable-hover-peek": {
        "type": "checkbox",
        "default": true,
        "description": "Show the window when hovering its thumbnail",
        "value": true
    },
    "hover-peek-time-in": {
        "dependency": "enable-hover-peek",
        "type": "combobox",
        "default": 300,
        "description": "Window fade-in time",
        "options": {
            "150 ms": 150,
            "300 ms": 300,
            "450 ms": 450
        },
        "value": 300
    },
    "hover-peek-time-out": {
        "dependency": "enable-hover-peek",
        "type": "combobox",
        "default": 0,
        "description": "Window fade-out time",
        "options": {
            "None": 0,
            "150 ms": 150,
            "300 ms": 300,
            "450 ms": 450
        },
        "value": 0
    },
    "hover-peek-opacity": {
        "dependency": "enable-hover-peek",
        "type": "spinbutton",
        "default": 100,
        "min": 0,
        "max": 100,
        "step": 1,
        "units": "percent",
        "description": "Window opacity",
        "value": 100
    },
    "__md5__": "c17a25f344a109cb1388da44a67375e8"
}
```
</details>

**Comment by kolayne** [comment]
Any news on this?

**Comment by kolayne** [comment]
Can reproduce it in Cinnamon 4.6.6

**Comment by icarter09** [comment]
@kolayne any way you could provide a video of this issue occurring? Thanks.

**Comment by kolayne** [comment]
Hi. Sure, here it is: https://youtu.be/M0dSCr4QfBI

**Comment by icarter09** [comment]
@kolayne thanks for the video. I was about to reproduce the issue.

**Comment by TechnologyMan101** [comment]
This does not happen on the old traditional Window List, only on Grouped Window List.

**Comment by kolayne** [comment]
> This does not happen on the old traditional Window List, only on Grouped Window List.

Yep. Just as stated in the issue's title

**Comment by icarter09** [comment]
@kolayne I put up a PR that should resolve this issue. If it doesn't, then just let me know and we'll step from there. Thanks.

**Comment by kolayne** [comment]
@icarter09 How do I check it?

**Comment by kolayne** [comment]
Is there any news?

**Comment by kolayne** [comment]
The issue persists in Cinnamon 4.8.5

**Comment by kolayne** [comment]
@gadass, I might have done something wrong, but it seems like #9819 does not fix the issue (see the video attached)

https://user-images.githubusercontent.com/23319866/104302888-6809ab80-54da-11eb-99be-a36f262cec4b.mp4

**Comment by kolayne** [comment]
I can't reproduce the issue anymore in Cinnamon 5.0.5. Hurray!
