### ISSUE TITLE
Error activating XKB configuration

### ISSUE THREAD

**Issue by spoo333** [linuxmint/cinnamon#9544]
```
 * Cinnamon version (cinnamon --version)
Cinnamon 4.4.8

   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
No
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu Cinnamon Remix 20.04
 * Graphics hardware *and* driver used
GeForce GTX 1650
Nvidia 440.100
 * 32 or 64 bit
64 bit
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[xsession-errors.zip](https://github.com/linuxmint/cinnamon/files/5133368/xsession-errors.zip)


 ```

**Issue**
On login or when trying to add an additional keyboard layout, the error message "error activating XKB configuration.
There can be various reasons for that.
If you report this situation as a bug, include the results of xprop -root | grep XKB

Output of xprop:
~$ xprop -root | grep XKB
_XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "applealu_iso", "gb", "mac", ""
_XKB_RULES_NAMES(STRING) = "evdev", "applealu_iso", "gb", "mac", ""

![Screenshot from 2020-08-26 19-24-19](https://user-images.githubusercontent.com/14813705/91371332-9d05b200-e808-11ea-9b57-5a67f7079864.png)

**Steps to reproduce**
Log into Cinnamon session
OR
Configure keyboard layouts/add second keyboard layout

The keyboard layouts are not displayed in the taskbar as usual

**Expected behaviour**
Login without the error message
Add keyboard layouts without the error message
Find the keyboard layout indicator in the taskbar

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by arnaghizadeh** [comment]
Hi, I have the same problem in ubuntu. Any solutions?

**Comment by spoo333** [comment]
Hello, I switched to Linux Mint. No problem there

**Comment by arnaghizadeh** [comment]
I fixed it by reconfiguring the default keboard layout from teminal: sudo dpkg-reconfigure keyboard-configuration.

**Comment by spoo333** [comment]
Great, thanks!

**Comment by kuntalkundu** [comment]
> I fixed it by reconfiguring the default keboard layout from teminal: sudo dpkg-reconfigure keyboard-configuration.

Thanks! It solved my problem in debian 11 Cinnamon. I had activated slick-greeter replacing lightdm-gtk-greeter. After log in to the session this error started to float on screen and my xkb keyboards setup were disappeared.

**Comment by AbdelrhmanUZaki** [comment]
> I fixed it by reconfiguring the default keboard layout from teminal: sudo dpkg-reconfigure keyboard-configuration.
thx!

**Comment by iofthetiger78** [comment]
Hi I am new to github and a beginner coder.  My linux mint has been giving me trouble with this error.  i ran the xprop command shown above and recieved this message:

XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "pc105", "us", "", ""
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

can anyone post some steps for me to follow to fix this?

**Comment by 3mmarYasser** [comment]
I was having the same problem on Parrot .
I fixed it just by setting the keyboard Model

**Comment by SandmanMw3** [comment]
for Parrot OS check this link and fix it
https://parrotsec.org/docs/configuration/assistive-technologies/

**Comment by MatzFan** [comment]
I got the "Error activating XKB configuration" error with a clean install of LMDE Faye on an old 7,2 (Intel) MacBook Air with an international keyboard (with the tilde/backtick key to the left of “z”). It isn't fixed by running `sudo dpkg-reconfigure keyboard-configuration` with any sensible combination I could find and the error shows on every boot or resume from hibernation. Also, all combinations of the above resulted in the tilde/backtick key mapped to “<”. The ±§ key to the left of “1” was mapped to backtick/tilde.

FWIW I also have Ubuntu 22.04 (Gnome) running on another, older, MacBook Air and have never got this error on that setup. The above keyboard mapping is wrong there too.

The bug alert asks for the output of some commands, so here it is:
```
$ xprop -root | grep XKB
_XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "macbook78", "us", "mac", ""
_XKB_RULES_NAMES(STRING) = "evdev", "macbook78", "us", "mac", ""
$ gsettings get org.gnome.libgnomekbd.keyboard model
''
$ gsettings get org.gnome.libgnomekbd.keyboard layouts
@as []
$ gsettings get org.gnome.libgnomekbd.keyboard options
['grp\tgrp:win_space_toggle', 'terminate\tterminate:ctrl_alt_bksp']
```

From the OP's original comment I see his/her system is also a Mac. There is also a [post](https://forums.linuxmint.com/viewtopic.php?t=260724) on the Linux Mint forums which mentions this error, again on a MacBook. I'd therefore suggest you might want to add "Mac" as a label to the bug.

A fix for the tilde/backtick mapping for me came from [here](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/334). I simply did:

`setxkbmap -model applealu_iso -layout gb`

The above command now shows this output:
```
$ xprop -root | grep XKB
_XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "macbook78", "us", "mac", ""
_XKB_RULES_NAMES(STRING) = "evdev", "applealu_iso", "gb", "", ""
```

To persist the changed I followed the instructions in the Arch wiki and did:
`sudo localectl --no-convert set-x11-keymap gb applealu_iso`

After restarting the X server with `sudo systemctl restart display-manager` I saw this:
```
$ xprop -root | grep XKB
_XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "applealu_iso", "gb", "", ""
_XKB_RULES_NAMES(STRING) = "evdev", "applealu_iso", "gb", "", ""
```

The keyboard mapping for tilde/backtick now persists after reboot, but alas I still get the "Error activating XKB configuration" error on startup.

In Settings, my keyboard layout still reads “English (UK, Macintosh)”.

**Comment by PredinAladin** [comment]
It wont work this for me

**Comment by PredinAladin** [comment]
I have linux mint cinnamon and the problem is the same, but the keyboard and mause wont work, and even the esc+fn dont work(normally the fn key lights up). It only works when i open the leptop and put he password, but then after a minute it stop working. I have an ASUS E210M and idk what to do, can someone help me? Pleeeeaaasssseeee. I cant even open the terminal.
