### ISSUE TITLE
Dual Monitors: Screen Lock and sleep moves windows to one monitor

### ISSUE THREAD

**Issue by cems2** [linuxmint/cinnamon#9659]
Yeah that's not going to work for all, specially if you need to rotate or position your screens (nvidia-settings might help). However, you have 2 choices. Either use another xrandr client like lxrandr or simply edit cinnamon-settings-daemon-xrandr.desktop (.config/autostart) and add **--exit-time**:

`Exec=/usr/lib/cinnamon-settings-daemon/csd-xrandr --exit-time 1`

_Originally posted by @bitstrings in https://github.com/linuxmint/cinnamon/issue_comments/403659500_

**Comment by jave808** [comment]
I can add a bit to this. My Issue #9655 only started when I installed a new Acer UHD monitor. I did not have this problem of windows "shifting" with my old setup - an AOC 27" 1920x1200 monitor as primary and a Dell 24" 1920x1200 monitor as secondary.
Maybe the fact that I had two monitors of the same resolution means something to someone?

**Comment by cems2** [comment]
@jave808  it may have to do with switching from HDMI to DP or another type for your UHD monitor.

**Comment by jave808** [comment]
@cems2 yes, this may be the case. My old AOC monitor was connected via a DP to DVI adapter on the video card side. DP port on video card and DVI port on monitor.

**Comment by iamapez** [comment]
Having the same issue here with 2 AOC monitors (215LM00055) connected to an AMD RX570 graphics card via HDMI. Pretty annoying bug, seems this issue has persisted for years with still no fix...

**Comment by nickstock** [comment]
My two pence worth... i run three identical monitors via display port and and don't have this issue, I did used to get it on a previous set up when using a mix of vga and dvi but now all three are on dp its is solid.

**Comment by jave808** [comment]
@nickstock yeah, my current setup is with a new Acer monitor and an old Dell monitor. I'm thinking of selling off the Dell for a newer Acer - not identical but with similar sleep characteristics. The Dell wakes up in an instant! I shouldn't have to go this far but it's an annoying bug.

**Comment by cems2** [comment]
the --exit-time 1 trick was working for me up until a recent update of linux mint. Now it fails one screen stays dark at boot and the other has it's settings unchangeable because of an error message saying the xrandr_2 is missing.  So I'm back to having all the windows coalesce onto one monitor every wake from sleep.  arg....
Linux Mint 20 Cinnamon version 4.6.7

**Comment by TheRocketSurgeon** [comment]
A simple permutation that I've not seen discussed - 3 identical monitors connected to onboard graphics, by HDMI, VGA and DVI. Directly removing power from VGA and DVI has no consequences to window layout. Removing HDMI power pushes all windows immediately to the VGA screen.

**Comment by cems2** [comment]
I think your observations are explained because the vga is analog so the computer can tell it is connected to a monitor but can't tell if the monitor is on.  DVI also has a analog optional channel so the same thing may be going on but I'm less sure.  HDMI is a fully handshaked digital connection so depowering it makes it seem unresponsive hence the monitor shift.
However I don't think this observation fits into the pathology being discussed in this issue.

**Comment by TheRocketSurgeon** [comment]
Yes, it certainly feels like like it's part of the HDMI protocol, but it's only happening on Cinnamon. Gnome 3.38 doesn't do this.

**Comment by brothertoad** [comment]
I saw this under Mint 18.3, but resolved it with the --exit-time option.  I upgraded (via reinstall) to 20.1 yesterday, and am seeing it again.  The --exit-time option does not seem to help.  I copied /etc/xdg/autostart/cinnamon-settings-daemon-xrandr.desktop to ~/.config/autostart and added the --exit-time.  I did not remove the original in /etc/xdg/autostart.  I have two identical monitors, ASUS 278PB, connected to a ASRock Radeon RX 570 graphics card via DisplayPort.  I've just noticed that one of my monitor goes blank for a few seconds every once in a while.  That is annoying, but nothing compared to the moving of windows to one screen.

**Comment by cems2** [comment]
It's not clear from your description if the extra steps you follwed 
after upgrading to 20.1 fixed the window coalescing problem or not. 
could you clarify this. also did you copy to "autostart" or append to 
the end of autostart?  What is also interesting is that you have two 
identical monitors and this still happens-- are your monitors connected 
via different interfaces?

**Comment by brothertoad** [comment]
Sorry I wasn't clear.  The problem is still occurring with 20.1.  My monitors are connected to the same graphics card, both via DisplayPort.  They are running at the same resolution.  I have noticed that when I wake the computer, the monitor on the left comes back to life a few seconds before the one on the right.  The one on the right is my primary screen, and this is where the windows all move to.

My autostart directory was empty to begin with.  (Note that this is my user-level directory, under ~/.config.)  This is a directory, not an ordinary file, so I'm not sure what you mean by "append".

I have since removed the file from my autostart directory, executed the following command

`dconf write /org/cinnamon/settings-daemon/plugins/xrandr/active false`

and to see if that fixes the problem, and I will update this post after more testing.

**Comment by brothertoad** [comment]
OK, the dconf command didn't fix it, but I did find a workaround.  It is similar to what worked before, but there was an extra step I was missing.  To work around this issue,

1. Copy /etc/xdg/autostart/cinnamon-settings-daemon-xrandr.desktop to ~/.config/autostart.
2. Open the ~/.config/autostart/cinnamon-settings-daemon-xrandr.desktop file in your favorite editor.  You will need to make two changes to this file.
3. First change is to add --exit-time 60 to the end of the Exec= line.  This causes the daemon to exit after 60 seconds.  You can use any value you want, but bear in mind that after the daemon exits, you won't be able to arrange monitors.
4. Second change - and this is what I was missing - is to change the value of X-GNOME-AutoRestart from true to false.  The default value is true, which causes the daemon to be restarted when it exits, thus effectively overriding the exit-time value.
5. Log out and log back in again.

I don't remember having to do step 4 on my old system, which was Linux Mint 18.3.  Sorry, but I don't know what version of Cinnamon that was.  The version I'm using now is 4.8, with Mint 20.1.

**Comment by twonintynine** [comment]
Uh, am I the only one that has noticed that HDMI has had horrible, horrible, wHOReRIBLE issues with standby/wake detection in the past, uh, forever?

yeah, all OS'es ASFAIK

**Comment by cems2** [comment]
@brothertoad   Could you annotate your work around so that I can understand what each step is doing?

**Comment by mxr576** [comment]
@brothertoad How does the fix you described is working so far? Is it still working? Any unexpected side effects so far?

**Comment by cems2** [comment]
Works. 

Currently after a system update I now have a different monitor problem of not being able to get it to recognize a second monitor attached after boot.  I suspect this be related but it didn't occur until a system update .

**Comment by brothertoad** [comment]
@j1elo I have loaded Zorin 16, which uses GNOME as its desktop, and the problem is there too, so it isn't just a Cinnamon bug.

**Comment by HighOnVoltage** [comment]
> Another confirmation here, the solution proposed in [#9659 (comment)](https://github.com/linuxmint/cinnamon/issues/9659#issuecomment-797158818) works for me too! Without any noticeable downside apart from the main known one (no further detection of monitors).

> Is this a bug in Cinnamon, or in xrandr? What should be the next steps to follow with this? I'm a software dev so I can work my way to provide whatever advanced feedback might be needed.

Running Debian 11 Buster with Cinnamon here, same issue. Seems like it doesn't matter what distro we use it's related to the WM or xrandr. @j1elo  Is there any suitable logs I can help with as KDE doesn't have this issue.

**Comment by fg-ok** [comment]
> > @brothertoad How does the fix you described is working so far? Is it still working? Any unexpected side effects so far?
> 
> Yes, it is still working fine. I have not seen any side effects.

I have encountered a quite annoying side effect. With the [solution](https://github.com/linuxmint/cinnamon/issues/9659#issuecomment-797158818) from brothertoad the problem with the windows on wrong monitor seems fixed, but if I had turned my secondary monitor off, and PC went to standby after waking the PC up again the primary monitor won't wake up, secondary monitor stays off.
So here I have to restart the window manager to get back in system.

**Comment by cxrodgers** [comment]
For me, disabling DPMS fixes this problem. You can type `xset -dpms` to disable it, and check whether it worked with `xset q`. In the past I've had issues with something turning DPMS back on, and fixed it by adding a cronjob to disable it every 10 minutes or so. I don't know if this is helpful for anyone just wanted to share my experience.

**Comment by hexarch** [comment]
I have two monitors, After screen lock, it moves main monitor to the right when it was on the left. Also after display the time for a few minutes, when I come back, it displays the time on the "now" main monitor and the second monitor shows the desktop, before locking.
This is not just a Cinnamon problem, Plasma is also terrible with dual monitors. Too many problems in one feature and plasma also disables the second monitor when playing a video... sometimes. Not consistent.
So for Cinnamon, the dual setup is also something that does not work. The only DE that is acceptable with dual monitor is Gnome.
Screen lock cannot show the desktop. Moving the primary monitor or changing monitors position cannot happen ever.
So this looks that is not only a Cinnamon problem. Any idea?

**Comment by slano** [comment]
The issue is still present on Linux Mint 21, but unfortunately, since csd-xrandr has been merged into Muffin, @brothertoad workaround doesn't work anymore (workaround was working just fine on 20.3).

Any idea what a next workaround should be?

**Comment by j1elo** [comment]
> The issue is still present on Linux Mint 21, but unfortunately, since csd-xrandr has been merged into Muffin, @brothertoad workaround doesn't work anymore (workaround was working just fine on 20.3).

Noooo, so we're back to square 1 again? :-(

> @j1elo Is there any suitable logs I can help with as KDE doesn't have this issue.

I'd need a bit of guidance to know which logs should be checked, as I'm still not even sure of what is the component that is causing this bug.

**Comment by georgehank** [comment]
*Why* is it so hard to just give the DE/WM an option "DO NOT REARRANGE WINDOWS EXCEPT WHEN I TURN OFF THIS OPTION OR I EXPLICITLY COMMAND YOU TO!".

Sheesh. 

(And I'm not even using Mint/Cinnamon, I'm on Devuan/XFCE4 but have the very same problem… obviously tied to DP/HDMI, but also to this "wonderful" new RX 6600 I just installed three days ago… my R9 380 didn't show any of this, but then again, only one monitor was connected via DP, while the other two were on DVI)
(Yes, Google brought me here, blame them ;-))

**Comment by allpoints** [comment]
I did not have this problem under "Linux Mint 20.1 Ulyssa".  However, I also was not able to get my screens to work properly using the standard, Cinnamon Preferences > Display GUI tool.   I had to resort to running the following on login.  Note that it was fine after that.  i.e. the screens restored as expected resuming from a screen lock.
```
xrandr --output eDP-1  --scale 1x1 --pos 2880x275
xrandr --output HDMI-1 --scale .75x.75
```
Where eDP-1 is an external monitor to the left of the laptop display, eDP-1

I have since rebuilt, not upgraded, the system with "Linux Mint 21 Vanessa".  The GUI tool now works as expected but I am also now experiencing this bug.

FWIW:
```
> inxi --no-host -SMGay
System:
  Kernel: 5.15.0-48-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    parameters: BOOT_IMAGE=/vmlinuz-5.15.0-48-generic
    root=/dev/mapper/vgmint-root ro quiet splash
  Desktop: Cinnamon 5.4.12 tk: GTK 3.24.33 wm: Mutter dm: LightDM 1.30.0
    Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Purism product: Librem 15 v3 v: 1.0
    serial: <superuser required> Chassis: type: 9 serial: <superuser required>
  Mobo: Purism model: Librem 15 v3 v: 1.0 serial: <superuser required>
    BIOS: coreboot v: 4.11-Purism-1 date: 11/26/2019
Graphics:
  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel ports:
    active: HDMI-A-1,eDP-1 empty: DP-1 bus-ID: 00:02.0 chip-ID: 8086:1916
    class-ID: 0300
  Device-2: Alcor Micro HD WebCam type: USB driver: uvcvideo bus-ID: 1-7:4
    chip-ID: 058f:d102 class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 9984x3456 s-dpi: 108 s-size: 2348x813mm (92.4x32.0")
    s-diag: 2485mm (97.8")
  Monitor-1: HDMI-1 mapped: HDMI-A-1 pos: primary,top-left
    model: Samsung U24E590 serial: HTPH400745 built: 2016 res: 6144x3456 hz: 30
    dpi: 300 gamma: 1.2 size: 521x293mm (20.5x11.5") diag: 598mm (23.5")
    ratio: 16:9 modes: max: 3840x2160 min: 720x400
  Monitor-2: eDP-1 pos: primary,bottom-r model: BOE Display built: 2014
    res: 3840x2160 hz: 60 dpi: 284 gamma: 1.2 size: 344x193mm (13.5x7.6")
    diag: 394mm (15.5") ratio: 16:9 modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 22.0.5
    direct render: Yes
```

**Comment by mtwebster** [comment]
@allpoints,

Please have a look at this comment: https://github.com/linuxmint/cinnamon-screensaver/issues/416#issuecomment-1256233029

I'm thinking the changes in those packages may address this issue also. The fixes should also be in the next cinnamon-screensaver release as well.

**Comment by allpoints** [comment]
@mtwebster,

I installed the https://github.com/linuxmint/cinnamon-screensaver/releases/tag/master.mint21 packages and the problem has been resolved.  Very much appreciated.  Thank you.

**Comment by ddouglas87** [comment]
I upgraded to Mint 21 a couple of days ago and am now having this issue where before I never did.  Some things of note:

- No changes to the NVidia driver.
- Display listed my 4k60 secondary monitor (a TV) as 30 fps for the first time, when it always showed 60 fps before.  This caused an audio video sync issue.  I went into my TV settings and switched HDMI from automatic mode to forced HDMI 2.0.  Display now shows 60 fps.  Odds by default it did 60 fps in all previous versions of Mint Cinnamon without issue.
- Now when my second monitor goes to sleep Cinnamon switches to mirrored mode removing my second desktop.
- When the second monitor comes on Cinnamon does not switch out of mirrored mode.  If I go to Display, change a setting, then click cancel on the setting change, it goes back to the proper dual display.

Given this is a brand new issue and there are other issues, it looks like something changed and my second monitor isn't being correctly detected any more, from the 30 fps to not recognizing sleep state.

I've had issues with all versions of Mint where if I turn off my primary monitor (manually, not sleep) there is about a 1 in 5 chance turning back on will have a blank screen I do not know how to get out of without a forceful reboot of the computer.  So this issue runs deeper than meets the eye.  When a monitor turns off the desktop should stick around, not disappear.  Have a setting in Display to disable this functionality for people who want Windows to merge when a monitor is turned off.  Imo in an ideal world each display is represented by a different workstation, so if you go from a dual monitor setup to a single monitor setup you can press a key bind that moves to the next workstation on the primary monitor.  This would be ideal, because few people ever want their desktop settings automatically messed with, they'd rather have a way to access the secondary screen on the primary screen.

**Comment by mattsmi** [comment]
I am seeing this in Linux Mint 21.1, new installation. Two screens using HDMI, one via a DELL Thunderbolt dock.
Have not seen it using the same version of Linux Mint on a different laptop with one screen using HDMI and the other using a display port — both directly connected to the laptop.
It is very annoying and confusing.
What I have also noted is that the number assigned to the screens (there are two external plus the laptop screen) changes. It seems to change after the windows move to a different screen. The numbers remain as set when you open the Display app, but when right-clicking an app and attempting to send it to a screen the numbers have all gone awry.

**Comment by Majki** [comment]
Linux Mint 21.1 Vera here, Cinnamon, I can confirm the bug is still here.

**Comment by allpoints** [comment]
I'm running 21/Vanessa but have kept it up to date.  The patches referenced above made it into the update cycle a few months ago and the problem was resolved for me.

For the maintainer, if you there's some specific hardware and/or config information you're interested in I'm happy to provide it.

**Comment by pine3ree** [comment]
Hello, I started having the same problem (21.1 xfce) a couple of days ago when I changed (only) my secondary monitor with a new monitor connected directly via hdmi. 

Before that I used an old (2008) LCD monitor  with vga-to-hdmi adapter without this issue. I also used the same old monitor vga-to-vga with 2 different laptops: one on mint-18-mate for years and before that one with ubuntu-lucid-gnome without this bug.

I remember that I also had the previous notebook (the one with mint-18-mate) coupled with a secondary hdmi-monitor of the same brand and features similar of the new one, without this bug.

**Comment by pine3ree** [comment]
In my case (xfce 21.1) I was able to solve the issue by saving a profile and setting "automatically configure monitors when connected" and "automatically load profiles for know monitors". Now all windows are in the original monitor and the frequency rate is preserved.

**Comment by nefarius** [comment]
For me adding `--exit-time 1` to `/etc/xdg/autostart/cinnamon-settings-daemon-xsettings.desktop` breaks the dark theme on various apps like Nemo, Virt manager etc. on `Linux Mint 21.3 Virginia`. No errors, just no longer applies the dark themes.

**Comment by giafitano-ux** [comment]
# Fix Monitor Configuration Reset After Hibernate on Debian Trixie (Cinnamon Desktop)

This guide was written for a Debian Trixie Cinnamon desktop with 3 monitors connected to an NVIDIA RTX 3080 Ti. Your monitor port names and resolutions will differ, but the process is the same.

## Step 1: Identify Your Monitors

From the terminal, run:
```bash
xrandr --query
```

This outputs multiple lines per monitor. Look for lines beginning with `HDMI-# connected` or `DP-# connected`:
```
Screen 0: minimum 320 x 200, current 7280 x 1440, maximum 16384 x 16384
DP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 598mm x 336mm  <-- This line
   1920x1080     71.91*+  59.96    60.00    59.94    59.93
   1680x1050     59.95    59.88
   1400x1050     59.98
   1600x900      59.94    59.95    60.00    59.82
   ... remaining lines truncated ...
```

In this example, all three monitors use DisplayPort, shown as `DP-1`, `DP-2`, and `DP-3`. If your monitors use HDMI, replace `DP` with `HDMI` throughout.

## Step 2: Note Your Monitor Configuration

From the `xrandr` output, find the "connected" monitors (non-relevant items removed):
```
DP-1 connected 1920x1080+0+0
DP-2 connected 1920x1080+5360+0
DP-3 connected primary 3440x1440+1920+0
```

The format is: `PORT MODE+XPOSITION+YPOSITION`

Breaking that down:

| Port | Resolution | Position |
|------|------------|----------|
| DP-1 | 1920x1080  | 0+0      |
| DP-2 | 1920x1080  | 5360+0   |
| DP-3 | 3440x1440  | 1920+0   |

In this example the physical monitor layout from left to right is:
```
DP-1    DP-3 (primary)    DP-2
```

This translates to the following xrandr arguments:
```
DP-1 --mode 1920x1080 --pos 0x0
DP-3 --mode 3440x1440 --pos 1920x0 --primary
DP-2 --mode 1920x1080 --pos 5360x0
```

## Step 3: Create the System Sleep Directory

The directory may not exist by default. Create it with:
```bash
sudo mkdir -p /lib/systemd/system-sleep
```

## Step 4: Create the Script
```bash
sudo nano /lib/systemd/system-sleep/fix-monitors.sh
```

Add the following, editing the `xrandr` section to match your configuration. Replace `<**username**>` with your username:
```bash
#!/bin/bash
if [ "$1" = "post" ] || [ "$2" = "hibernate" ] || [ "$2" = "hybrid-sleep" ]; then
    sleep 6
    export DISPLAY=:0
    export XAUTHORITY=/home/<**username**>/.Xauthority
    xrandr --output DP-1 --mode 1920x1080 --pos 0x0 \
           --output DP-3 --mode 3440x1440 --pos 1920x0 --primary \
           --output DP-2 --mode 1920x1080 --pos 5360x0
fi
```

Save with `Ctrl+O`, then exit with `Ctrl+X`.

## Step 5: Make the Script Executable
```bash
sudo chmod +x /lib/systemd/system-sleep/fix-monitors.sh
```

## Step 6: Test

First, test the script manually to confirm your monitors arrange correctly:
```bash
sudo /lib/systemd/system-sleep/fix-monitors.sh post suspend
```

Your monitors should briefly flicker and settle into the correct layout. Then test with a real hibernate cycle:
```bash
systemctl hibernate
```

Wake the machine and verify the monitor layout is correct.

## Notes

- If the layout still resets after hibernate, try increasing the `sleep 6` delay to `sleep 10` or higher. Hibernation can take longer to restore depending on how much RAM is in use.
- The `sleep` directory at `/lib/systemd/system-sleep/` is automatically scanned by systemd — no additional registration of the script is needed.

**Comment by sshermz** [comment]
I'm experiencing this on Linux Mint 21.3 Cinnamon using an IO Gear KVM switch to share a monitor w/a MB Pro. Same issue as it only occurs after awakening Mint.

Is a proper fix feasible for this issue? If not, how about a new option to lock the mode as @georgehank suggested? Or alternatively a new option to choose the default mode (i.e. Extended instead of Mirrored)?

BTW, why is Mirrored mode the default? I would guess that most users use Extended mode.
