### ISSUE TITLE
Grouped Window List forces windows into a specific order

### ISSUE THREAD

**Issue by yigitdnz** [linuxmint/cinnamon#9802]
```
 * Cinnamon version 4.8.4
 * Distribution - Arch
 * Graphics hardware used Intel HD4000
 * 64 bit
 
 ```
**Issue**
The order of the windows on the panel sometimes changes when I close one of the windows. 

I've taken 3 screenshots to show the issue:

Initially 3 Firefox windows and 1 Google Chrome window are open. 
The titles of 2 of the Firefox windows are rightmost and leftmost.
Then I open another application window.
When I close the newly opened application window, the order of the list changes. 
Notice the leftmost Firefox moved rightwards, Google Chrome window moved leftwards etc.)

![1](https://user-images.githubusercontent.com/8185376/103285364-0253f480-49ef-11eb-94e3-4d0882cd54c7.png)
![2](https://user-images.githubusercontent.com/8185376/103285375-0849d580-49ef-11eb-810e-0b95d1cd3de7.png)
![3](https://user-images.githubusercontent.com/8185376/103285377-0b44c600-49ef-11eb-9c69-da2ee40f240b.png)

**Steps to reproduce**
Open a couple of windows. Close one of them and observe. If nothing happens change the order of the windows and then open and close one window again.

**Expected behaviour**
The order of the windows to remain unchanged.

**Other information**
I don't know what information is relevant to provide so I just add the GWL settings file.
[gwl-settings.json.zip](https://github.com/linuxmint/cinnamon/files/5750732/gwl-settings.json.zip)

**Comment by furrykef** [comment]
I'm having this issue as well, and it's profoundly annoying. It started when I upgraded to Mint 20.1.

**Comment by furrykef** [comment]
For what it's worth, I've noticed this issue doesn't appear for me in the CobiWindowList applet. So a workaround might be to use that or a similar applet instead of the system "Grouped window list" applet.

**Comment by proffase** [comment]
Same issue for me with automatic program list re-ordering when I close any app.
Happens since upgrade to 20.1.

**Comment by ronyala** [comment]
Hi, I am able to replicate this using the configuration file, so it's probably a broken setting somewhere.
Resetting the settings of `Grouped Window List` fixes it for me.

**Comment by yigitdnz** [comment]
> Hi, I am able to replicate this using the configuration file, so it's probably a broken setting somewhere.
> Resetting the settings of `Grouped Window List` fixes it for me.

thanks. resetting the applet and reapplying the same settings through applet preferences worked for me

**Comment by briandavidclark** [comment]
Resetting the applet and reapplying the settings does **not** work for me.

**Comment by firepainting** [comment]
Hi. I missed this issue and seems I made a duplicate, #9845.

I'm also just reporting that this has been persisting on my 2 Mint PCs since I upgraded to 20.1 Ulyssa from 20 Ulyana.

Resetting GWL does **not** solve it. However, issue does not happen with CobiWindowList.

@ronyala thanks for pointing me here.

**Comment by RachidTagzen** [comment]
Issue still exists even after reseting "Grouped Window List" applet.
This annoying problem appeared after updating from Linux Mint 20 to 20.1.

**Comment by lazarin** [comment]
I hit the same issue and no matter of the configuration I tried, resetting and reloading GWL always reorders the buttons after closing an window.
Is there a way how to revert GWL to the version used in Mint 20 till this is resolved?

**Comment by ronyala** [comment]
Hi, I added a PR #9899 that fixes it for me.
This stops it most of the time.
Note that it will still happen when closing a pinned window in ungrouped-windows mode, as to prevent other issues (4c1aa69b4662c7091e5a2d29e72aa404ad801424).

**Comment by mm-manu** [comment]
This is really annoying, my multi-window application is now scattered all over the taskbar. Window grouping is not an option for me. Looking forward to the fix.

**Comment by ronyala** [comment]
@mm-manu
I updated the PR, so now list refreshes should never happen when closing a window.

**Comment by furrykef** [comment]
I don't understand why the PR hasn't been merged in yet. This bug negatively impacts the entire time the user is using the computer. I don't mean it annoys me once in a blue moon, I mean I am _constantly_ looking for where my programs have decided to put themselves on the taskbar instead of simply remembering where they should be. I understand this issue may not be as urgent to the Cinnamon devs as it is to me, but the PR has been available for nearly a full month now, and I can't tell if anyone has so much as glanced at it.

**Comment by BWPanda** [comment]
I couldn't wait, so I applied the PR/patch to my system manually, and it seems to be working nicely so far! Thanks @ronyala & @mtwebster!

**Comment by GinGin3203** [comment]
The issue is still present for me on Cinnamon 5.0.3.

Hitting `Global hotkey to show the order of apps` keybinding seems to fix it though.
